foreach (required_variable IN ITEMS SOURCE_DIRECTORY WORK_DIRECTORY HOST_GENERATOR)
    if (NOT DEFINED ${required_variable})
        message(FATAL_ERROR "${required_variable} is required")
    endif ()
endforeach ()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef TEST_NONCE)
set(TEST_ROOT "${WORK_DIRECTORY}/huxerui-android-app-${TEST_NONCE}")
set(PROJECT_ROOT "${TEST_ROOT}/source")
file(MAKE_DIRECTORY "${PROJECT_ROOT}")
file(WRITE "${PROJECT_ROOT}/main.cpp" "int main() { return 0; }\n")
# Exercise application artifact generation with the host compiler, independently of the Android SDK and framework.
set(PROJECT_CONTENT [=[
cmake_minimum_required(VERSION 3.20)
project(android_app_integration LANGUAGES CXX)
include("@SOURCE_DIRECTORY@/cmake/HuxerUIApp.cmake")
function(_huxerui_select_framework_target output)
    set(${output} framework PARENT_SCOPE)
endfunction()
function(huxerui_enable_codegen target_name)
endfunction()
function(_huxerui_append_resource_package_input target_name package)
endfunction()
add_library(framework INTERFACE)
set_property(TARGET framework PROPERTY HUXERUI_RESOURCE_PACKAGE unused)
set(ANDROID TRUE)
set(APPLE FALSE)
set(IOS FALSE)
huxerui_add_app(${APP_TARGET} SOURCES main.cpp)
set_target_properties(${APP_TARGET} PROPERTIES PREFIX "lib" SUFFIX ".so")
if (APP_OUTPUT)
    set_target_properties(${APP_TARGET} PROPERTIES OUTPUT_NAME "${APP_OUTPUT}" DEBUG_POSTFIX "_debug")
endif ()
]=])
string(CONFIGURE "${PROJECT_CONTENT}" PROJECT_CONTENT @ONLY)
file(WRITE "${PROJECT_ROOT}/CMakeLists.txt" "${PROJECT_CONTENT}")

function(check_app_plan abi configuration target_name output_name expected_name)
    set(BUILD_ROOT "${TEST_ROOT}/build-${abi}-${configuration}")
    set(INTEGRATION_ROOT "${TEST_ROOT}/integration/${configuration}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${PROJECT_ROOT}" -B "${BUILD_ROOT}" -G "${HOST_GENERATOR}"
            "-DCMAKE_BUILD_TYPE=${configuration}" "-DAPP_TARGET=${target_name}" "-DAPP_OUTPUT=${output_name}"
            "-DANDROID_ABI=${abi}" "-DHUXERUI_ANDROID_APP_INTEGRATION_ROOT=${INTEGRATION_ROOT}"
            RESULT_VARIABLE CONFIGURE_RESULT OUTPUT_VARIABLE CONFIGURE_OUTPUT ERROR_VARIABLE CONFIGURE_ERROR)
    if (NOT CONFIGURE_RESULT EQUAL 0)
        message(FATAL_ERROR "Android application configure failed:\n${CONFIGURE_OUTPUT}${CONFIGURE_ERROR}")
    endif ()
    file(READ "${INTEGRATION_ROOT}/${abi}/app.json" APP_PLAN)
    string(JSON RESOLVED_TARGET GET "${APP_PLAN}" target)
    string(JSON RESOLVED_ARTIFACT GET "${APP_PLAN}" artifact)
    get_filename_component(RESOLVED_NAME "${RESOLVED_ARTIFACT}" NAME)
    if (NOT RESOLVED_TARGET STREQUAL target_name OR NOT RESOLVED_NAME STREQUAL expected_name)
        message(FATAL_ERROR "Unexpected Android application integration plan: ${APP_PLAN}")
    endif ()
endfunction()

foreach (ABI IN ITEMS arm64-v8a x86_64)
    check_app_plan("${ABI}" Debug sample_app "" libsample_app.so)
    # Reuse the build directory so later properties and target renames cannot leave stale metadata.
    check_app_plan("${ABI}" Debug sample_app custom_player libcustom_player_debug.so)
    check_app_plan("${ABI}" Debug renamed_app "" librenamed_app.so)
    check_app_plan("${ABI}" Release renamed_app custom_player libcustom_player.so)
endforeach ()
