include_guard(GLOBAL)
cmake_policy(PUSH)
cmake_policy(VERSION 3.20)

function(huxerui_add_runtime_dependencies target_name)
    if (NOT TARGET ${target_name})
        message(FATAL_ERROR "HuxerUI runtime dependency owner does not exist: ${target_name}")
    endif ()
    get_property(graph_only TARGET ${target_name} PROPERTY HUXERUI_LIBRARY_GRAPH_ONLY)
    if (graph_only)
        return()
    endif ()
    get_target_property(owner_kind ${target_name} TYPE)
    if (NOT owner_kind STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "HuxerUI runtime dependencies require a desktop application target: ${target_name}")
    endif ()
    cmake_parse_arguments(PARSE_ARGV 1 runtime "" "DESTINATION" "TARGETS;FILES;SEARCH_DIRECTORIES")
    if (runtime_UNPARSED_ARGUMENTS OR runtime_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "HuxerUI invalid runtime dependency arguments for ${target_name}")
    endif ()
    if (DEFINED runtime_DESTINATION)
        if (IS_ABSOLUTE "${runtime_DESTINATION}" OR runtime_DESTINATION MATCHES "(^|[/\\])\\.\\.([/\\]|$)")
            message(FATAL_ERROR "HuxerUI runtime DESTINATION must stay inside the application: ${runtime_DESTINATION}")
        endif ()
    else ()
        set(runtime_DESTINATION "@default")
    endif ()
    foreach (dependency IN LISTS runtime_TARGETS)
        if (NOT TARGET ${dependency})
            message(FATAL_ERROR "HuxerUI runtime dependency target does not exist: ${dependency}")
        endif ()
        get_target_property(kind ${dependency} TYPE)
        if (NOT kind MATCHES "^(SHARED|MODULE)_LIBRARY$")
            message(FATAL_ERROR "HuxerUI runtime dependency must be a shared library or module: ${dependency}")
        endif ()
        get_target_property(imported ${dependency} IMPORTED)
        if (NOT imported)
            add_dependencies(${target_name} ${dependency})
        endif ()
        list(APPEND runtime_FILES "$<TARGET_FILE:${dependency}>")
        _huxerui_runtime_link_directories(${dependency} directories)
        list(APPEND runtime_SEARCH_DIRECTORIES ${directories})
    endforeach ()
    get_property(inputs TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INPUT_SCRIPTS)
    list(LENGTH inputs index)
    set(input "${CMAKE_CURRENT_BINARY_DIR}/huxerui-runtime/${target_name}/$<CONFIG>/dependencies-${index}.cmake")
    set(script "set(files [==[${runtime_FILES}]==])\nset(destination [==[${runtime_DESTINATION}]==])\n")
    string(APPEND script "set(declaration_directory [==[${CMAKE_CURRENT_SOURCE_DIR}]==])\n")
    string(APPEND script [=[
foreach(file IN LISTS files)
    if(NOT file STREQUAL "")
        get_filename_component(file "${file}" ABSOLUTE BASE_DIR "${declaration_directory}")
        list(APPEND extra_files "${file}")
        list(APPEND extra_destinations "${destination}")
    endif()
endforeach()
]=])
    string(APPEND script "set(directories [==[${runtime_SEARCH_DIRECTORIES}]==])\n")
    string(APPEND script [=[
foreach(directory IN LISTS directories)
    if(NOT directory STREQUAL "")
        get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${declaration_directory}")
        list(APPEND search_directories "${directory}")
    endif()
endforeach()
]=])
    # Imported targets are visible in the declaring directory, not necessarily at the project root.
    file(GENERATE OUTPUT "${input}" CONTENT "${script}" TARGET ${target_name})
    set_property(TARGET ${target_name} APPEND PROPERTY HUXERUI_RUNTIME_INPUT_SCRIPTS "${input}")
endfunction()

function(_huxerui_install_runtime_dependencies target_name component content_directory executable)
    get_property(registered TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INSTALL_COMPONENT)
    if (registered)
        message(FATAL_ERROR "HuxerUI runtime deployment is already registered for ${target_name}")
    endif ()
    set_property(TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INSTALL_COMPONENT "${component}")
    set_property(TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_CONTENT_DIRECTORY "${content_directory}")
    set_property(TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_EXECUTABLE "${executable}")
    set_property(TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INSTALL_SCRIPT
            "${CMAKE_BINARY_DIR}/huxerui-runtime/${target_name}/$<CONFIG>/install.cmake")
    if (APPLE)
        target_link_options(${target_name} PRIVATE -Wl,-headerpad_max_install_names)
    endif ()
    get_property(scheduled DIRECTORY PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS)
    set_property(DIRECTORY APPEND PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS ${target_name})
    if (NOT scheduled)
        cmake_language(DEFER CALL _huxerui_generate_runtime_installs)
    endif ()
    get_property(registered GLOBAL PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS)
    set_property(GLOBAL APPEND PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS ${target_name})
    if (NOT registered)
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL _huxerui_install_runtime_scripts)
    endif ()
endfunction()

function(_huxerui_install_runtime_scripts)
    get_property(targets GLOBAL PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS)
    foreach (target_name IN LISTS targets)
        get_property(script TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INSTALL_SCRIPT)
        get_property(component TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_INSTALL_COMPONENT)
        install(SCRIPT "${script}" COMPONENT "${component}")
    endforeach ()
endfunction()

function(_huxerui_runtime_link_directories target_name output)
    set(pending ${target_name})
    set(visited)
    set(directories)
    while (pending)
        list(POP_FRONT pending dependency)
        if (NOT TARGET "${dependency}" OR dependency IN_LIST visited)
            continue()
        endif ()
        list(APPEND visited "${dependency}")
        get_target_property(kind ${dependency} TYPE)
        if (kind MATCHES "^(SHARED|MODULE)_LIBRARY$")
            list(APPEND directories "$<TARGET_FILE_DIR:${dependency}>")
        endif ()
        foreach (property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_property(links TARGET ${dependency} PROPERTY ${property})
            foreach (link IN LISTS links)
                if (link MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE):([^<>]+)>$")
                    set(link "${CMAKE_MATCH_2}")
                endif ()
                if (TARGET "${link}")
                    list(APPEND pending "${link}")
                endif ()
            endforeach ()
        endforeach ()
    endwhile ()
    set(${output} "${directories}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_find_msvc_redist output compiler toolset architecture)
    set(candidates)
    file(TO_CMAKE_PATH "${compiler}" compiler)
    if (compiler MATCHES "^(.+)/VC/Tools/MSVC/([^/]+)/bin/Host[^/]+/[^/]+/[^/]+$")
        set(redist_root "${CMAKE_MATCH_1}/VC/Redist/MSVC")
        list(APPEND candidates "${redist_root}/${CMAKE_MATCH_2}")
        if (toolset)
            list(APPEND candidates "${redist_root}/v${toolset}")
        endif ()
    endif ()
    if (DEFINED ENV{VCToolsRedistDir} AND NOT "$ENV{VCToolsRedistDir}" STREQUAL "")
        file(TO_CMAKE_PATH "$ENV{VCToolsRedistDir}" environment_redist)
        list(APPEND candidates "${environment_redist}")
    endif ()
    list(REMOVE_DUPLICATES candidates)
    foreach (candidate IN LISTS candidates)
        file(GLOB runtime_files "${candidate}/${architecture}/Microsoft.*.CRT/*.dll")
        if (runtime_files)
            get_filename_component(candidate "${candidate}" ABSOLUTE)
            set(${output} "${candidate}" PARENT_SCOPE)
            return()
        endif ()
    endforeach ()
    set(${output} "" PARENT_SCOPE)
endfunction()

function(_huxerui_generate_runtime_installs)
    get_property(targets DIRECTORY PROPERTY HUXERUI_RUNTIME_INSTALL_TARGETS)
    if (WIN32)
        get_filename_component(compiler_directory "${CMAKE_CXX_COMPILER}" DIRECTORY)
        find_program(runtime_tool dumpbin HINTS "${compiler_directory}" REQUIRED)
        set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
        set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_NO_WARNINGS TRUE)
        set(CMAKE_INSTALL_DEBUG_LIBRARIES FALSE)
        set(CMAKE_INSTALL_DEBUG_LIBRARIES_ONLY FALSE)
        set(CMAKE_INSTALL_UCRT_LIBRARIES FALSE)
        set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
        set(redist_was_configured FALSE)
        if (DEFINED MSVC_REDIST_DIR AND NOT "${MSVC_REDIST_DIR}" MATCHES "-NOTFOUND$")
            set(redist_was_configured TRUE)
            set(configured_redist_directory "${MSVC_REDIST_DIR}")
        endif ()
        include(InstallRequiredSystemLibraries)
        set(redist_files ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS})
        if (redist_was_configured)
            set(redist_directory "${configured_redist_directory}")
        elseif (MSVC_REDIST_DIR AND IS_DIRECTORY "${MSVC_REDIST_DIR}")
            set(redist_directory "${MSVC_REDIST_DIR}")
        else ()
            _huxerui_runtime_find_msvc_redist(redist_directory
                    "${CMAKE_CXX_COMPILER}" "${MSVC_TOOLSET_VERSION}" "${CMAKE_MSVC_ARCH}")
        endif ()
        if (redist_directory AND CMAKE_MSVC_ARCH)
            file(GLOB additional_redist_files "${redist_directory}/${CMAKE_MSVC_ARCH}/Microsoft.*/*.dll")
            list(APPEND redist_files ${additional_redist_files})
        endif ()
        list(REMOVE_DUPLICATES redist_files)
        # Compiler and redistributable file builds may differ within the same toolset release.
        if (CMAKE_CXX_COMPILER MATCHES "/Tools/MSVC/([0-9.]+)/")
            set(minimum_crt "${CMAKE_MATCH_1}")
        else ()
            string(REGEX REPLACE "^19\\.([0-9]+).*" "14.\\1" minimum_crt "${CMAKE_CXX_COMPILER_VERSION}")
        endif ()
        set(runtime_platform windows+pe)
        set(runtime_tool_name dumpbin)
    elseif (APPLE)
        find_program(runtime_tool otool REQUIRED)
        set(runtime_platform macos+macho)
        set(runtime_tool_name otool)
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_program(runtime_tool NAMES "${CMAKE_OBJDUMP}" objdump REQUIRED)
        set(runtime_platform linux+elf)
        set(runtime_tool_name objdump)
    else ()
        message(FATAL_ERROR "HuxerUI runtime deployment is unavailable for ${CMAKE_SYSTEM_NAME}")
    endif ()
    foreach (target_name IN LISTS targets)
        foreach (property IN ITEMS INSTALL_SCRIPT CONTENT_DIRECTORY EXECUTABLE)
            get_property(${property} TARGET ${target_name} PROPERTY HUXERUI_RUNTIME_${property})
        endforeach ()
        _huxerui_runtime_link_directories(${target_name} SEARCH_DIRECTORIES)
        list(APPEND SEARCH_DIRECTORIES "$<TARGET_FILE_DIR:${target_name}>")
        list(REMOVE_DUPLICATES SEARCH_DIRECTORIES)
        set(script "include([==[${CMAKE_CURRENT_FUNCTION_LIST_DIR}/HuxerUIRuntimeDependencies.cmake]==])\n")
        if (WIN32 AND HUXERUI_WINDOWS_7_COMPAT)
            string(APPEND script "message(FATAL_ERROR \"HuxerUI runtime packaging requires the default Windows 10 platform; Windows 7 redistribution is not configured\")\n")
        endif ()
        foreach (variable IN ITEMS runtime_platform runtime_tool runtime_tool_name redist_files minimum_crt)
            string(APPEND script "set(${variable} [==[${${variable}}]==])\n")
        endforeach ()
        string(APPEND script "set(search_directories [==[${SEARCH_DIRECTORIES}]==])\n")
        string(APPEND script "set(deployment_target [==[${CMAKE_OSX_DEPLOYMENT_TARGET}]==])\n")
        string(APPEND script "set(inputs [==[$<GENEX_EVAL:$<TARGET_PROPERTY:${target_name},HUXERUI_RUNTIME_INPUT_SCRIPTS>>]==])\n")
        string(APPEND script [=[
set(extra_files)
set(extra_destinations)
foreach(input IN LISTS inputs)
    include("${input}")
endforeach()
list(REMOVE_ITEM search_directories "")
list(REMOVE_DUPLICATES search_directories)
]=])
        string(APPEND script
                "_huxerui_deploy_runtime([==[$<TARGET_FILE:${target_name}>]==] [==[${CONTENT_DIRECTORY}]==] [==[${EXECUTABLE}]==])\n")
        file(GENERATE OUTPUT "${INSTALL_SCRIPT}" CONTENT "${script}" TARGET ${target_name})
    endforeach ()
endfunction()

function(_huxerui_runtime_command output)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE value ERROR_VARIABLE error
            OUTPUT_STRIP_TRAILING_WHITESPACE)
    if (NOT result STREQUAL "0")
        message(FATAL_ERROR "HuxerUI runtime deployment command failed (${ARGN}): ${error}${value}")
    endif ()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_binary file output_kind output_architecture)
    set(kind)
    set(architecture)
    if (EXISTS "${file}" AND NOT IS_DIRECTORY "${file}")
        file(SIZE "${file}" size)
        file(READ "${file}" magic LIMIT 4 HEX)
        if (runtime_platform STREQUAL "windows+pe" AND magic MATCHES "^4d5a" AND size GREATER_EQUAL 64)
            file(READ "${file}" offset OFFSET 60 LIMIT 4 HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "\\4\\3\\2\\1" offset "${offset}")
            math(EXPR offset "0x${offset}")
            math(EXPR header_end "${offset} + 24")
            set(header)
            if (offset GREATER_EQUAL 64 AND header_end LESS_EQUAL size)
                file(READ "${file}" header OFFSET ${offset} LIMIT 24 HEX)
            endif ()
            if (header MATCHES "^50450000")
                string(SUBSTRING "${header}" 8 4 architecture)
                string(SUBSTRING "${header}" 46 2 flags)
                math(EXPR dll "0x${flags} & 0x20")
                if (dll)
                    set(kind LIBRARIES)
                else ()
                    set(kind EXECUTABLES)
                endif ()
                set(architecture "pe-${architecture}")
            endif ()
        elseif (runtime_platform STREQUAL "linux+elf" AND magic STREQUAL "7f454c46" AND size GREATER_EQUAL 52)
            file(READ "${file}" format OFFSET 4 LIMIT 2 HEX)
            file(READ "${file}" type OFFSET 16 LIMIT 2 HEX)
            file(READ "${file}" machine OFFSET 18 LIMIT 2 HEX)
            if (format MATCHES "^0[12]0[12]$" AND (format MATCHES "^01" OR size GREATER_EQUAL 64))
                if (type MATCHES "^(0200|0002)$")
                    set(kind EXECUTABLES)
                elseif (type MATCHES "^(0300|0003)$")
                    set(kind LIBRARIES)
                endif ()
                set(architecture "elf-${format}-${machine}")
            endif ()
        elseif (runtime_platform STREQUAL "macos+macho" AND size GREATER_EQUAL 28
                AND magic MATCHES "^(feedface|feedfacf|cefaedfe|cffaedfe|cafebabe|bebafeca|cafebabf|bfbafeca)$")
            # A Java class shares the fat Mach-O magic; let the native tools validate the complete header.
            execute_process(COMMAND "${lipo}" -archs "${file}" RESULT_VARIABLE result
                    OUTPUT_VARIABLE architecture ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
            if (result STREQUAL "0")
                separate_arguments(architecture)
                execute_process(COMMAND "${runtime_tool}" -hv "${file}" RESULT_VARIABLE result
                        OUTPUT_VARIABLE header ERROR_QUIET)
                if (result STREQUAL "0")
                    if (header MATCHES "[ \t]EXECUTE[ \t]")
                        set(kind EXECUTABLES)
                    elseif (header MATCHES "[ \t]BUNDLE[ \t]")
                        set(kind MODULES)
                    elseif (header MATCHES "[ \t]DYLIB[ \t]")
                        set(kind LIBRARIES)
                    endif ()
                endif ()
            endif ()
        endif ()
    endif ()
    set(${output_kind} "${kind}" PARENT_SCOPE)
    set(${output_architecture} "${architecture}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_check_architecture file kind architecture)
    if (NOT kind)
        message(FATAL_ERROR "HuxerUI runtime dependency is not a supported binary: ${file}")
    endif ()
    foreach (required IN LISTS required_architecture)
        if (NOT required IN_LIST architecture)
            message(FATAL_ERROR "HuxerUI runtime architecture mismatch: ${file} (${architecture}), expected ${required_architecture}")
        endif ()
    endforeach ()
endfunction()

function(_huxerui_runtime_inputs path output)
    if (NOT EXISTS "${path}")
        message(FATAL_ERROR "HuxerUI runtime dependency is missing: ${path}")
    endif ()
    if (IS_DIRECTORY "${path}")
        if (NOT runtime_platform STREQUAL "macos+macho" OR NOT path MATCHES "\\.(framework|bundle)/?$")
            message(FATAL_ERROR "HuxerUI runtime dependency directory must be a framework or bundle: ${path}")
        endif ()
        file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${path}/*")
        set(binaries)
        foreach (file IN LISTS files)
            _huxerui_runtime_binary("${file}" kind architecture)
            if (kind)
                file(REAL_PATH "${file}" file)
                list(APPEND binaries "${file}")
            endif ()
        endforeach ()
        list(REMOVE_DUPLICATES binaries)
        if (NOT binaries)
            message(FATAL_ERROR "HuxerUI runtime bundle contains no binary: ${path}")
        endif ()
    else ()
        set(binaries "${path}")
    endif ()
    set(${output} "${binaries}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_scan output)
    set(EXECUTABLES)
    set(LIBRARIES)
    set(MODULES)
    list(APPEND scan_roots ${ARGN})
    foreach (file IN LISTS ARGN)
        _huxerui_runtime_binary("${file}" kind architecture)
        _huxerui_runtime_check_architecture("${file}" "${kind}" "${architecture}")
        if (file STREQUAL scan_executable)
            set(kind EXECUTABLES)
        endif ()
        list(APPEND ${kind} "${file}")
    endforeach ()
    file(GET_RUNTIME_DEPENDENCIES EXECUTABLES ${EXECUTABLES} LIBRARIES ${LIBRARIES} MODULES ${MODULES}
            BUNDLE_EXECUTABLE "${scan_executable}"
            DIRECTORIES ${search_directories}
            PRE_EXCLUDE_REGEXES ${pre_excludes}
            RESOLVED_DEPENDENCIES_VAR resolved
            UNRESOLVED_DEPENDENCIES_VAR unresolved
            CONFLICTING_DEPENDENCIES_PREFIX conflicts
    )
    if (runtime_platform STREQUAL "macos+macho" AND unresolved AND search_directories)
        set(missing)
        foreach (dependency IN LISTS unresolved)
            string(REGEX REPLACE "^@(rpath|loader_path|executable_path)/" "" relative "${dependency}")
            set(found)
            foreach (directory IN LISTS search_directories)
                set(candidate "${directory}/${relative}")
                if (EXISTS "${candidate}" AND NOT IS_DIRECTORY "${candidate}")
                    file(REAL_PATH "${candidate}" candidate)
                    if (found AND NOT found STREQUAL candidate)
                        message(FATAL_ERROR "HuxerUI ambiguous runtime dependency ${dependency}: ${found};${candidate}")
                    endif ()
                    set(found "${candidate}")
                endif ()
            endforeach ()
            if (found)
                list(APPEND resolved "${found}")
                if (NOT found IN_LIST scan_roots)
                    _huxerui_runtime_scan(nested "${found}")
                    list(APPEND resolved ${nested})
                endif ()
            else ()
                list(APPEND missing "${dependency}")
            endif ()
        endforeach ()
        set(unresolved ${missing})
    endif ()
    if (unresolved)
        message(FATAL_ERROR "HuxerUI unresolved runtime dependencies for ${ARGN}: ${unresolved}\nSearch directories: ${search_directories}")
    endif ()
    foreach (name IN LISTS conflicts_FILENAMES)
        set(previous)
        foreach (file IN LISTS conflicts_${name})
            file(SHA256 "${file}" hash)
            if (previous AND NOT previous STREQUAL hash)
                message(FATAL_ERROR "HuxerUI conflicting runtime dependency ${name}: ${conflicts_${name}}")
            endif ()
            set(previous "${hash}")
            list(APPEND resolved "${file}")
        endforeach ()
    endforeach ()
    set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_copy source directory output_sources output_destinations)
    get_filename_component(name "${source}" NAME)
    set(copy_source "${source}")
    if (runtime_platform STREQUAL "macos+macho" AND source MATCHES "^(.+\\.(framework|bundle))(/.*)?$")
        set(copy_source "${CMAKE_MATCH_1}")
        get_filename_component(name "${copy_source}" NAME)
    endif ()
    if (IS_DIRECTORY "${copy_source}")
        if (IS_DIRECTORY "${directory}/${name}")
            file(GLOB_RECURSE source_entries LIST_DIRECTORIES TRUE RELATIVE "${copy_source}" "${copy_source}/*")
            file(GLOB_RECURSE installed_entries LIST_DIRECTORIES TRUE RELATIVE "${directory}/${name}" "${directory}/${name}/*")
            if (NOT source_entries STREQUAL installed_entries)
                message(FATAL_ERROR "HuxerUI conflicting runtime bundle: ${copy_source} and ${directory}/${name}")
            endif ()
        endif ()
        file(GLOB_RECURSE relative_files LIST_DIRECTORIES FALSE RELATIVE "${copy_source}" "${copy_source}/*")
        set(input_files)
        foreach (relative IN LISTS relative_files)
            list(APPEND input_files "${copy_source}/${relative}")
        endforeach ()
    else ()
        set(input_files "${source}")
        set(link "${source}")
        while (IS_SYMLINK "${link}")
            file(READ_SYMLINK "${link}" next)
            get_filename_component(parent "${link}" DIRECTORY)
            get_filename_component(link "${next}" ABSOLUTE BASE_DIR "${parent}")
            if (link IN_LIST input_files OR NOT EXISTS "${link}")
                message(FATAL_ERROR "HuxerUI invalid runtime symbolic link: ${source}")
            endif ()
            list(APPEND input_files "${link}")
        endwhile ()
        get_filename_component(copy_source "${copy_source}" DIRECTORY)
        set(name "")
    endif ()
    set(sources)
    set(destinations)
    foreach (file IN LISTS input_files)
        if (name)
            file(RELATIVE_PATH relative "${copy_source}" "${file}")
        else ()
            get_filename_component(relative "${file}" NAME)
        endif ()
        set(destination "${directory}/${name}/${relative}")
        cmake_path(NORMAL_PATH destination)
        if (EXISTS "${destination}")
            file(SHA256 "${file}" source_hash)
            file(SHA256 "${destination}" destination_hash)
            if (NOT source_hash STREQUAL destination_hash)
                message(FATAL_ERROR "HuxerUI conflicting runtime payload: ${file} and ${destination}")
            endif ()
        endif ()
        _huxerui_runtime_binary("${file}" kind architecture)
        if (kind)
            _huxerui_runtime_check_architecture("${file}" "${kind}" "${architecture}")
            file(REAL_PATH "${file}" real_source)
            list(APPEND sources "${real_source}")
            list(APPEND destinations "${destination}")
        endif ()
    endforeach ()
    if (name)
        file(COPY "${copy_source}" DESTINATION "${directory}")
        file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE RELATIVE "${copy_source}" "${copy_source}/*")
        foreach (entry IN LISTS entries)
            if (IS_SYMLINK "${copy_source}/${entry}")
                file(REAL_PATH "${copy_source}/${entry}" linked)
                file(RELATIVE_PATH relative "${copy_source}" "${linked}")
                if (NOT EXISTS "${linked}" OR IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\./")
                    message(FATAL_ERROR "HuxerUI runtime bundle has a broken or external link: ${copy_source}/${entry}")
                endif ()
                get_filename_component(parent "${directory}/${name}/${entry}" DIRECTORY)
                file(RELATIVE_PATH relative "${parent}" "${directory}/${name}/${relative}")
                file(REMOVE "${directory}/${name}/${entry}")
                file(CREATE_LINK "${relative}" "${directory}/${name}/${entry}" SYMBOLIC)
            endif ()
        endforeach ()
    else ()
        file(COPY "${source}" DESTINATION "${directory}" FOLLOW_SYMLINK_CHAIN)
        file(REAL_PATH "${source}" real_source)
        get_filename_component(real_name "${real_source}" NAME)
        set(sources "${real_source}")
        set(destinations "${directory}/${real_name}")
    endif ()
    set(${output_sources} "${sources}" PARENT_SCOPE)
    set(${output_destinations} "${destinations}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_windows_crt mode output)
    set(crt)
    set(pending ${ARGN})
    while (pending)
        list(POP_FRONT pending file)
        _huxerui_runtime_command(imports "${runtime_tool}" /DEPENDENTS "${file}")
        string(TOLOWER "${imports}" imports)
        string(REGEX MATCHALL "[a-z0-9_.-]+\\.dll" imports "${imports}")
        foreach (name IN LISTS imports)
            if (name MATCHES "^(ucrtbased|msvcp[0-9]+(_[0-9]+)?d.*|vcruntime[0-9]+d.*|vcruntime[0-9]+_[0-9]+d|msvcr[0-9]+d|concrt[0-9]+d|vcomp[0-9]+d|mfc[0-9]+u?d)\\.dll$")
                message(FATAL_ERROR "HuxerUI cannot package the Debug VC++ runtime ${name}, required by ${file}")
            endif ()
            if (NOT name MATCHES "${crt_regex}")
                continue()
            endif ()
            if (mode STREQUAL "verify")
                set(runtime "${library_directory}/${name}")
                if (NOT EXISTS "${runtime}")
                    message(FATAL_ERROR "HuxerUI packaged VC++ runtime ${name} is missing, required by ${file}")
                endif ()
            else ()
                set(runtime)
                foreach (candidate IN LISTS redist_files)
                    get_filename_component(candidate_name "${candidate}" NAME)
                    string(TOLOWER "${candidate_name}" candidate_name)
                    if (candidate_name STREQUAL name AND EXISTS "${candidate}")
                        set(runtime "${candidate}")
                        break()
                    endif ()
                endforeach ()
                if (NOT runtime)
                    message(FATAL_ERROR "HuxerUI VC++ Release redistributable ${name} is missing from the toolchain Redist directory, required by ${file}")
                endif ()
                if (runtime IN_LIST crt)
                    continue()
                endif ()
                string(REPLACE "'" "''" escaped_runtime "${runtime}")
                _huxerui_runtime_command(version powershell -NoProfile -NonInteractive -Command
                        "([Diagnostics.FileVersionInfo]::GetVersionInfo('${escaped_runtime}')).FileVersion")
                if (version VERSION_LESS minimum_crt)
                    message(FATAL_ERROR "HuxerUI VC++ runtime ${runtime} (${version}) is older than the toolchain (${minimum_crt})")
                endif ()
            endif ()
            _huxerui_runtime_binary("${runtime}" kind architecture)
            _huxerui_runtime_check_architecture("${runtime}" "${kind}" "${architecture}")
            if (NOT runtime IN_LIST crt)
                list(APPEND pending "${runtime}")
            endif ()
            list(APPEND crt "${runtime}")
        endforeach ()
    endwhile ()
    list(REMOVE_DUPLICATES crt)
    set(${output} "${crt}" PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_system_file file system_dependencies output)
    get_filename_component(name "${file}" NAME)
    if (runtime_platform STREQUAL "windows+pe")
        string(TOLOWER "${name}" name)
    endif ()
    set(system FALSE)
    foreach (pattern IN LISTS system_excludes)
        if (name MATCHES "${pattern}" OR file MATCHES "${pattern}")
            set(system TRUE)
        endif ()
    endforeach ()
    if (desktop_runtime_regex AND name MATCHES "${desktop_runtime_regex}")
        set(system TRUE)
    endif ()
    foreach (dependency IN LISTS system_dependencies)
        get_filename_component(system_name "${dependency}" NAME)
        if (name STREQUAL system_name)
            set(system TRUE)
        endif ()
    endforeach ()
    set(${output} ${system} PARENT_SCOPE)
endfunction()

function(_huxerui_runtime_collect source_executable extra_files output_dependencies output_system)
    set(roots "${source_executable}")
    set(explicit_binaries)
    foreach (path IN LISTS extra_files)
        _huxerui_runtime_inputs("${path}" binaries)
        foreach (file IN LISTS binaries)
            _huxerui_runtime_system_file("${file}" "" system)
            if (system)
                message(FATAL_ERROR "HuxerUI cannot explicitly deploy a system runtime: ${file}")
            endif ()
            file(REAL_PATH "${file}" file)
            list(APPEND explicit_binaries "${file}")
        endforeach ()
        list(APPEND roots ${binaries})
    endforeach ()
    list(REMOVE_DUPLICATES roots)
    _huxerui_runtime_scan(resolved ${roots})
    set(system_dependencies)
    if (runtime_platform STREQUAL "linux+elf")
        foreach (dependency IN LISTS resolved)
            file(REAL_PATH "${dependency}" real_dependency)
            if (real_dependency IN_LIST system_dependencies)
                continue()
            endif ()
            _huxerui_runtime_system_file("${dependency}" "${system_dependencies}" system)
            if (system)
                if (NOT real_dependency MATCHES "^/(usr/)?lib(64)?/")
                    message(FATAL_ERROR "HuxerUI requires the distribution-owned desktop runtime: ${dependency}")
                endif ()
                _huxerui_runtime_scan(system_closure "${dependency}")
                foreach (system_file IN ITEMS "${dependency}" ${system_closure})
                    file(REAL_PATH "${system_file}" system_file)
                    if (NOT system_file MATCHES "^/(usr/)?lib(64)?/")
                        message(FATAL_ERROR "HuxerUI distribution runtime depends on a non-system file: ${system_file}")
                    endif ()
                    list(APPEND system_dependencies "${system_file}")
                endforeach ()
            endif ()
        endforeach ()
        list(REMOVE_DUPLICATES system_dependencies)
        foreach (file IN LISTS explicit_binaries)
            if (file IN_LIST system_dependencies)
                message(FATAL_ERROR "HuxerUI cannot explicitly deploy a system runtime: ${file}")
            endif ()
        endforeach ()
    elseif (runtime_platform STREQUAL "windows+pe")
        _huxerui_runtime_windows_crt(resolve crt ${roots} ${resolved})
        if (crt)
            _huxerui_runtime_scan(crt_dependencies ${crt})
            list(APPEND resolved ${crt} ${crt_dependencies})
        endif ()
    endif ()
    list(REMOVE_DUPLICATES resolved)
    set(${output_dependencies} "${resolved}" PARENT_SCOPE)
    set(${output_system} "${system_dependencies}" PARENT_SCOPE)
endfunction()

function(_huxerui_deploy_runtime source_executable content_directory executable)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM "${runtime_platform}")
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL "${runtime_tool_name}")
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${runtime_tool}")
    set(content_directory "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${content_directory}")
    cmake_path(NORMAL_PATH content_directory)
    set(installed_executable "${content_directory}/${executable}")
    if (NOT EXISTS "${installed_executable}")
        message(FATAL_ERROR "HuxerUI installed executable is missing: ${installed_executable}")
    endif ()
    set(scan_executable "${source_executable}")
    set(desktop_runtime_regex)
    if (runtime_platform STREQUAL "windows+pe")
        set(library_directory "${content_directory}")
        set(crt_regex "^(msvcp[0-9]+.*|msvcr[0-9]+.*|vcruntime[0-9]+.*|concrt[0-9]+.*|vcomp[0-9]+.*|mfc[0-9]+.*|ucrtbased)\\.dll$")
        set(windows_system_libraries
                advapi32 avrt bcrypt bcryptprimitives cabinet cfgmgr32 clbcatq combase comctl32 comdlg32
                crypt32 cryptbase cryptsp d2d1 d3d9 d3d11 d3d12 dcomp dhcpcsvc dnsapi dsound dwmapi dwrite dxgi
                faultrep gdi32 gdi32full hid imm32 iphlpapi kernel32 kernelbase mf mfplat mfreadwrite mfuuid
                mpr msacm32 msimg32 msvcrt mswsock ncrypt netapi32 ntdll normaliz ole32 oleacc oleaut32
                opengl32 powrprof propsys psapi rasapi32 rpcrt4 secur32 setupapi shcore shell32 shlwapi
                sspicli user32 userenv usp10 uxtheme uiautomationcore ucrtbase version wer win32u windowsapp
                windowscodecs winhttp wininet winmm winspool wintrust wldap32 ws2_32 wsock32 wtsapi32)
        string(JOIN "|" windows_system_names ${windows_system_libraries})
        set(system_excludes "^(api-ms-|ext-ms-)" "^(${windows_system_names})\\.dll$")
    elseif (runtime_platform STREQUAL "macos+macho")
        find_program(lipo lipo REQUIRED)
        find_program(install_name_tool install_name_tool REQUIRED)
        find_program(codesign codesign REQUIRED)
        set(library_directory "${content_directory}/Frameworks")
        set(system_excludes "^/System/Library/" "^/usr/lib/")
    else ()
        find_program(patchelf patchelf REQUIRED)
        find_program(readelf readelf REQUIRED)
        set(library_directory "${content_directory}/lib")
        set(system_excludes "^ld-linux.*" "^lib(c|m|dl|pthread|rt|resolv|util|anl|BrokenLocale)\\.so(\\.[0-9]+)*$"
                "^libstdc\\+\\+\\.so\\.6$" "^libgcc_s\\.so\\.1$")
        set(desktop_runtime_regex "^lib(gtk-4|epoxy|gio-2\\.0|glib-2\\.0|gobject-2\\.0|pango-1\\.0|cairo|soup-3\\.0|EGL|GL|GLX|GLdispatch|OpenGL|GLESv[12]|vulkan|drm)\\.so(\\.|$)")
    endif ()
    set(pre_excludes ${system_excludes})
    if (runtime_platform STREQUAL "windows+pe")
        list(APPEND pre_excludes "${crt_regex}")
    endif ()
    _huxerui_runtime_binary("${source_executable}" kind required_architecture)
    if (NOT kind)
        message(FATAL_ERROR "HuxerUI runtime deployment cannot inspect ${source_executable}")
    endif ()
    _huxerui_runtime_collect("${source_executable}" "${extra_files}" resolved system_dependencies)
    file(REAL_PATH "${source_executable}" real_executable)
    set(sources "${real_executable}")
    set(destinations "${installed_executable}")
    list(LENGTH extra_files extra_count)
    if (extra_count)
        math(EXPR last "${extra_count} - 1")
        foreach (index RANGE ${last})
            list(GET extra_files ${index} path)
            list(GET extra_destinations ${index} destination)
            if (destination STREQUAL "@default")
                set(destination "${library_directory}")
                if (runtime_platform STREQUAL "macos+macho" AND path MATCHES "\\.bundle(/|$)")
                    set(destination "${content_directory}/PlugIns")
                endif ()
            else ()
                if (IS_ABSOLUTE "${destination}" OR destination MATCHES "(^|[/\\])\\.\\.([/\\]|$)")
                    message(FATAL_ERROR "HuxerUI runtime DESTINATION must stay inside the application: ${destination}")
                endif ()
                set(destination "${content_directory}/${destination}")
            endif ()
            _huxerui_runtime_copy("${path}" "${destination}" copied_sources copied_destinations)
            list(APPEND sources ${copied_sources})
            list(APPEND destinations ${copied_destinations})
        endforeach ()
    endif ()
    foreach (dependency IN LISTS resolved)
        file(REAL_PATH "${dependency}" real_dependency)
        if (real_dependency IN_LIST system_dependencies)
            continue()
        endif ()
        list(FIND sources "${real_dependency}" existing)
        if (existing GREATER_EQUAL 0)
            list(GET destinations ${existing} installed)
            get_filename_component(installed_directory "${installed}" DIRECTORY)
            file(REAL_PATH "${installed_directory}" installed_directory)
            file(REAL_PATH "${library_directory}" default_directory)
            if (NOT installed_directory STREQUAL default_directory)
                continue()
            endif ()
        endif ()
        _huxerui_runtime_copy("${dependency}" "${library_directory}" copied_sources copied_destinations)
        list(APPEND sources ${copied_sources})
        list(APPEND destinations ${copied_destinations})
    endforeach ()
    set(unique_sources)
    set(unique_destinations)
    list(LENGTH sources source_count)
    math(EXPR last_source "${source_count} - 1")
    foreach (index RANGE ${last_source})
        list(GET sources ${index} source)
        list(GET destinations ${index} destination)
        file(REAL_PATH "${destination}" destination)
        list(FIND unique_sources "${source}" previous)
        if (previous GREATER_EQUAL 0)
            list(GET unique_destinations ${previous} previous_destination)
            if (NOT previous_destination STREQUAL destination)
                message(FATAL_ERROR "HuxerUI runtime dependency has multiple destinations: ${source}")
            endif ()
        else ()
            list(APPEND unique_sources "${source}")
            list(APPEND unique_destinations "${destination}")
        endif ()
    endforeach ()
    set(sources ${unique_sources})
    set(destinations ${unique_destinations})
    if (NOT runtime_platform STREQUAL "windows+pe")
        file(CHMOD ${destinations} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    endif ()
    if (runtime_platform STREQUAL "linux+elf")
        _huxerui_runtime_fix_linux("${destinations}" "${library_directory}")
    elseif (runtime_platform STREQUAL "macos+macho")
        _huxerui_runtime_fix_macos("${sources}" "${destinations}" "${library_directory}" "${installed_executable}")
    endif ()
    _huxerui_runtime_verify("${content_directory}" "${installed_executable}" "${library_directory}" "${system_dependencies}")
    message(STATUS "HuxerUI runtime dependencies deployed and verified: ${installed_executable}")
endfunction()

function(_huxerui_runtime_verify content_directory installed_executable library_directory system_dependencies)
    set(scan_executable "${installed_executable}")
    set(search_directories)
    if (runtime_platform STREQUAL "windows+pe")
        set(search_directories "${library_directory}")
    endif ()
    file(GLOB_RECURSE staged_files LIST_DIRECTORIES TRUE "${content_directory}/*")
    set(staged_binaries)
    foreach (file IN LISTS staged_files)
        if (IS_SYMLINK "${file}")
            file(REAL_PATH "${file}" linked)
            file(RELATIVE_PATH relative "${content_directory}" "${linked}")
            if (NOT EXISTS "${file}" OR IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\./")
                message(FATAL_ERROR "HuxerUI packaged symbolic link is broken or external: ${file}")
            endif ()
        endif ()
        _huxerui_runtime_binary("${file}" kind architecture)
        if (kind)
            _huxerui_runtime_check_architecture("${file}" "${kind}" "${architecture}")
            _huxerui_runtime_system_file("${file}" "${system_dependencies}" system)
            if (system)
                message(FATAL_ERROR "HuxerUI packaged files must not contain a system runtime: ${file}")
            endif ()
            file(REAL_PATH "${file}" file)
            list(APPEND staged_binaries "${file}")
        endif ()
    endforeach ()
    list(REMOVE_DUPLICATES staged_binaries)
    _huxerui_runtime_scan(final_dependencies ${staged_binaries})
    foreach (dependency IN LISTS final_dependencies)
        file(REAL_PATH "${dependency}" dependency)
        file(RELATIVE_PATH relative "${content_directory}" "${dependency}")
        if ((IS_ABSOLUTE "${relative}" OR relative MATCHES "^\\.\\./") AND NOT dependency IN_LIST system_dependencies)
            message(FATAL_ERROR "HuxerUI packaged runtime still depends on an external file: ${dependency}")
        endif ()
    endforeach ()
    if (runtime_platform STREQUAL "windows+pe")
        _huxerui_runtime_windows_crt(verify ignored ${staged_binaries})
    elseif (runtime_platform STREQUAL "macos+macho")
        set(signing_paths ${staged_binaries})
        # Signing the main executable also seals its bundle, which must follow all nested code.
        file(REAL_PATH "${installed_executable}" main_executable)
        list(REMOVE_ITEM signing_paths "${main_executable}")
        foreach (file IN LISTS staged_files)
            if (IS_DIRECTORY "${file}" AND file MATCHES "\\.(framework|bundle)$")
                list(APPEND signing_paths "${file}")
            endif ()
        endforeach ()
        list(SORT signing_paths ORDER DESCENDING)
        foreach (file IN LISTS signing_paths)
            if (file MATCHES "\\.framework$" AND IS_DIRECTORY "${file}/Versions")
                file(GLOB versions LIST_DIRECTORIES TRUE "${file}/Versions/*")
                foreach (version IN LISTS versions)
                    if (IS_DIRECTORY "${version}" AND NOT IS_SYMLINK "${version}")
                        get_filename_component(version "${version}" NAME)
                        _huxerui_runtime_command(ignored "${codesign}" --force --sign - --bundle-version "${version}" "${file}")
                    endif ()
                endforeach ()
            endif ()
            _huxerui_runtime_command(ignored "${codesign}" --force --sign - "${file}")
        endforeach ()
        get_filename_component(bundle "${content_directory}" DIRECTORY)
        _huxerui_runtime_command(ignored "${codesign}" --force --sign - "${bundle}")
        _huxerui_runtime_command(ignored "${codesign}" --verify --deep --strict "${bundle}")
    else ()
        set(abi_versions)
        foreach (file IN LISTS staged_binaries)
            _huxerui_runtime_command(versions "${readelf}" --version-info "${file}")
            string(REGEX MATCHALL "(GLIBC|GLIBCXX|CXXABI)_[0-9.]+" versions "${versions}")
            list(APPEND abi_versions ${versions})
        endforeach ()
        foreach (abi IN ITEMS GLIBC GLIBCXX CXXABI)
            set(minimum 0)
            foreach (version IN LISTS abi_versions)
                if (version MATCHES "^${abi}_([0-9.]+)$" AND CMAKE_MATCH_1 VERSION_GREATER minimum)
                    set(minimum "${CMAKE_MATCH_1}")
                endif ()
            endforeach ()
            if (NOT minimum STREQUAL "0")
                message(STATUS "HuxerUI packaged runtime requires ${abi}_${minimum}")
            endif ()
        endforeach ()
    endif ()
endfunction()

function(_huxerui_runtime_fix_linux destinations library_directory)
    foreach (file IN LISTS destinations)
        get_filename_component(directory "${file}" DIRECTORY)
        file(RELATIVE_PATH relative_library_directory "${directory}" "${library_directory}")
        set(rpath "$ORIGIN")
        if (relative_library_directory)
            string(APPEND rpath ":$ORIGIN/${relative_library_directory}")
        endif ()
        _huxerui_runtime_command(ignored "${patchelf}" --set-rpath "${rpath}" "${file}")
        _huxerui_runtime_command(needed "${patchelf}" --print-needed "${file}")
        string(REPLACE "\n" ";" needed "${needed}")
        foreach (dependency IN LISTS needed)
            if (IS_ABSOLUTE "${dependency}")
                get_filename_component(name "${dependency}" NAME)
                _huxerui_runtime_command(ignored "${patchelf}" --replace-needed "${dependency}" "${name}" "${file}")
            endif ()
        endforeach ()
    endforeach ()
endfunction()

function(_huxerui_runtime_fix_macos sources destinations library_directory installed_executable)
    list(LENGTH sources count)
    math(EXPR last "${count} - 1")
    foreach (index RANGE ${last})
        list(GET sources ${index} source)
        list(GET destinations ${index} destination)
        _huxerui_runtime_command(load_commands "${runtime_tool}" -l "${destination}")
        if (deployment_target)
            string(REGEX MATCHALL "minos [0-9.]+|cmd LC_VERSION_MIN_MACOSX\n[ \t]+cmdsize [0-9]+\n[ \t]+version [0-9.]+" versions "${load_commands}")
            foreach (version IN LISTS versions)
                string(REGEX MATCH "[0-9.]+$" version "${version}")
                if (version VERSION_GREATER deployment_target)
                    message(FATAL_ERROR "HuxerUI runtime dependency ${source} requires macOS ${version}, above ${deployment_target}")
                endif ()
            endforeach ()
        endif ()
        _huxerui_runtime_command(imports "${runtime_tool}" -L "${destination}")
        string(REGEX MATCHALL "\n[ \t]+[^\n]+ \\(compatibility version" imports "${imports}")
        foreach (line IN LISTS imports)
            string(REGEX REPLACE "^\n[ \t]+| \\(compatibility version$" "" dependency "${line}")
            if (dependency MATCHES "^(/usr/lib/|/System/Library/)")
                continue()
            endif ()
            get_filename_component(dependency_name "${dependency}" NAME)
            set(replacement)
            set(resolved_source)
            set(installed_dependency)
            if (IS_ABSOLUTE "${dependency}" AND EXISTS "${dependency}")
                file(REAL_PATH "${dependency}" resolved_source)
            elseif (dependency MATCHES "^@rpath/(.+)$")
                set(installed_dependency "${library_directory}/${CMAKE_MATCH_1}")
            endif ()
            if (installed_dependency AND EXISTS "${installed_dependency}")
                file(REAL_PATH "${installed_dependency}" installed)
                file(RELATIVE_PATH relative "${library_directory}" "${installed}")
                set(replacement "@rpath/${relative}")
            endif ()
            set(exact_replacement "${replacement}")
            foreach (candidate_index RANGE ${last})
                if (exact_replacement)
                    break()
                endif ()
                list(GET sources ${candidate_index} candidate)
                get_filename_component(candidate_name "${candidate}" NAME)
                if ((resolved_source AND candidate STREQUAL resolved_source)
                        OR (NOT resolved_source AND candidate_name STREQUAL dependency_name))
                    list(GET destinations ${candidate_index} installed)
                    file(RELATIVE_PATH relative "${library_directory}" "${installed}")
                    set(current "@rpath/${relative}")
                    if (replacement AND NOT replacement STREQUAL current)
                        message(FATAL_ERROR "HuxerUI ambiguous Mach-O dependency ${dependency} in ${source}")
                    endif ()
                    set(replacement "${current}")
                endif ()
            endforeach ()
            if (NOT replacement)
                message(FATAL_ERROR "HuxerUI cannot relocate Mach-O dependency ${dependency} in ${source}")
            endif ()
            _huxerui_runtime_command(ignored "${install_name_tool}" -change "${dependency}" "${replacement}" "${destination}")
        endforeach ()
        _huxerui_runtime_binary("${destination}" kind architecture)
        if (kind STREQUAL "LIBRARIES")
            file(RELATIVE_PATH relative "${library_directory}" "${destination}")
            _huxerui_runtime_command(ignored "${install_name_tool}" -id "@rpath/${relative}" "${destination}")
        endif ()
        string(REGEX MATCHALL "cmd LC_RPATH\n[ \t]+cmdsize [0-9]+\n[ \t]+path [^\n]+ \\(offset [0-9]+\\)" rpaths "${load_commands}")
        set(old_rpaths)
        foreach (entry IN LISTS rpaths)
            string(REGEX REPLACE "^.*\n[ \t]+path | \\(offset [0-9]+\\)$" "" entry "${entry}")
            list(APPEND old_rpaths "${entry}")
        endforeach ()
        list(REMOVE_DUPLICATES old_rpaths)
        foreach (entry IN LISTS old_rpaths)
            _huxerui_runtime_command(ignored "${install_name_tool}" -delete_rpath "${entry}" "${destination}")
        endforeach ()
        get_filename_component(directory "${destination}" DIRECTORY)
        file(RELATIVE_PATH relative "${directory}" "${library_directory}")
        if (destination STREQUAL installed_executable)
            set(rpath "@executable_path/../Frameworks")
        elseif (relative)
            set(rpath "@loader_path/${relative}")
        else ()
            set(rpath "@loader_path")
        endif ()
        _huxerui_runtime_command(ignored "${install_name_tool}" -add_rpath "${rpath}" "${destination}")
    endforeach ()
endfunction()

cmake_policy(POP)
