dialog_ok = موافق
dialog_cancel = إلغاء
progress_in_progress = قيد التقدم
refresh = تحديث
text_selection_cut = قص
text_selection_copy = نسخ
text_selection_paste = لصق
text_selection_select_all = تحديد الكل
window_minimize = تصغير
window_maximize = تكبير
window_restore = استعادة
window_close = إغلاق
validation_required = هذا الحقل مطلوب
validation_email = أدخل عنوان بريد إلكتروني صالحًا
