dialog_ok = موافق
dialog_cancel = إلغاء
progress_in_progress = قيد التقدم
refresh = تحديث
text_selection_cut = قص
text_selection_copy = نسخ
text_selection_paste = لصق
text_selection_select_all = تحديد الكل
window_minimize = تصغير
window_maximize = تكبير
window_restore = استعادة
window_close = إغلاق
validation_required = هذا الحقل مطلوب
validation_email = أدخل عنوان بريد إلكتروني صالحًا
date_picker = منتقي التاريخ
date_picker_previous_month = الشهر السابق
date_picker_next_month = الشهر التالي
date_picker_previous_years = السنوات السابقة
date_picker_next_years = السنوات التالية
date_picker_choose_year = اختيار السنة
date_picker_month_january = يناير
date_picker_month_february = فبراير
date_picker_month_march = مارس
date_picker_month_april = أبريل
date_picker_month_may = مايو
date_picker_month_june = يونيو
date_picker_month_july = يوليو
date_picker_month_august = أغسطس
date_picker_month_september = سبتمبر
date_picker_month_october = أكتوبر
date_picker_month_november = نوفمبر
date_picker_month_december = ديسمبر
date_picker_weekday_sunday = أحد
date_picker_weekday_monday = إثنين
date_picker_weekday_tuesday = ثلاثاء
date_picker_weekday_wednesday = أربعاء
date_picker_weekday_thursday = خميس
date_picker_weekday_friday = جمعة
date_picker_weekday_saturday = سبت
time_picker = منتقي الوقت
time_picker_hour = الساعة
time_picker_minute = الدقيقة
time_picker_am = ص
time_picker_pm = م
