dialog_ok = ঠিক আছে
dialog_cancel = বাতিল
progress_in_progress = চলছে
refresh = রিফ্রেশ
text_selection_cut = কাটুন
text_selection_copy = কপি করুন
text_selection_paste = পেস্ট করুন
text_selection_select_all = সব নির্বাচন করুন
window_minimize = ছোট করুন
window_maximize = বড় করুন
window_restore = পুনরুদ্ধার করুন
window_close = বন্ধ করুন
validation_required = এই ক্ষেত্রটি আবশ্যক
validation_email = একটি বৈধ ইমেল ঠিকানা লিখুন
date_picker = তারিখ নির্বাচক
date_picker_previous_month = আগের মাস
date_picker_next_month = পরের মাস
date_picker_previous_years = আগের বছরগুলো
date_picker_next_years = পরের বছরগুলো
date_picker_choose_year = বছর বেছে নিন
date_picker_month_january = জানুয়ারি
date_picker_month_february = ফেব্রুয়ারি
date_picker_month_march = মার্চ
date_picker_month_april = এপ্রিল
date_picker_month_may = মে
date_picker_month_june = জুন
date_picker_month_july = জুলাই
date_picker_month_august = আগস্ট
date_picker_month_september = সেপ্টেম্বর
date_picker_month_october = অক্টোবর
date_picker_month_november = নভেম্বর
date_picker_month_december = ডিসেম্বর
date_picker_weekday_sunday = রঃ
date_picker_weekday_monday = সোঃ
date_picker_weekday_tuesday = মঃ
date_picker_weekday_wednesday = বুঃ
date_picker_weekday_thursday = বৃঃ
date_picker_weekday_friday = শুঃ
date_picker_weekday_saturday = শনি
time_picker = সময় নির্বাচক
time_picker_hour = ঘণ্টা
time_picker_minute = মিনিট
time_picker_am = AM
time_picker_pm = PM
