dialog_ok = ঠিক আছে
dialog_cancel = বাতিল
progress_in_progress = চলছে
refresh = রিফ্রেশ
text_selection_cut = কাটুন
text_selection_copy = কপি করুন
text_selection_paste = পেস্ট করুন
text_selection_select_all = সব নির্বাচন করুন
window_minimize = ছোট করুন
window_maximize = বড় করুন
window_restore = পুনরুদ্ধার করুন
window_close = বন্ধ করুন
validation_required = এই ক্ষেত্রটি আবশ্যক
validation_email = একটি বৈধ ইমেল ঠিকানা লিখুন
