dialog_ok = OK
dialog_cancel = Zrušit
progress_in_progress = Probíhá
refresh = Obnovit
text_selection_cut = Vyjmout
text_selection_copy = Kopírovat
text_selection_paste = Vložit
text_selection_select_all = Vybrat vše
window_minimize = Minimalizovat
window_maximize = Maximalizovat
window_restore = Obnovit
window_close = Zavřít
validation_required = Toto pole je povinné
validation_email = Zadejte platnou e-mailovou adresu
date_picker = Výběr data
date_picker_previous_month = Předchozí měsíc
date_picker_next_month = Další měsíc
date_picker_previous_years = Předchozí roky
date_picker_next_years = Další roky
date_picker_choose_year = Vybrat rok
date_picker_month_january = leden
date_picker_month_february = únor
date_picker_month_march = březen
date_picker_month_april = duben
date_picker_month_may = květen
date_picker_month_june = červen
date_picker_month_july = červenec
date_picker_month_august = srpen
date_picker_month_september = září
date_picker_month_october = říjen
date_picker_month_november = listopad
date_picker_month_december = prosinec
date_picker_weekday_sunday = ne
date_picker_weekday_monday = po
date_picker_weekday_tuesday = út
date_picker_weekday_wednesday = st
date_picker_weekday_thursday = čt
date_picker_weekday_friday = pá
date_picker_weekday_saturday = so
time_picker = Výběr času
time_picker_hour = Hodina
time_picker_minute = Minuta
time_picker_am = dop.
time_picker_pm = odp.
