dialog_ok = OK
dialog_cancel = Zrušit
progress_in_progress = Probíhá
refresh = Obnovit
text_selection_cut = Vyjmout
text_selection_copy = Kopírovat
text_selection_paste = Vložit
text_selection_select_all = Vybrat vše
window_minimize = Minimalizovat
window_maximize = Maximalizovat
window_restore = Obnovit
window_close = Zavřít
validation_required = Toto pole je povinné
validation_email = Zadejte platnou e-mailovou adresu
