dialog_ok = OK
dialog_cancel = Annuller
progress_in_progress = I gang
text_selection_cut = Klip
text_selection_copy = Kopiér
text_selection_paste = Sæt ind
text_selection_select_all = Markér alt
window_minimize = Minimer
window_maximize = Maksimer
window_restore = Gendan
window_close = Luk
validation_required = Dette felt er påkrævet
validation_email = Angiv en gyldig mailadresse
