dialog_ok = OK
dialog_cancel = Annuller
progress_in_progress = I gang
refresh = Opdater
text_selection_cut = Klip
text_selection_copy = Kopiér
text_selection_paste = Sæt ind
text_selection_select_all = Markér alt
window_minimize = Minimer
window_maximize = Maksimer
window_restore = Gendan
window_close = Luk
validation_required = Dette felt er påkrævet
validation_email = Angiv en gyldig mailadresse
date_picker = Datovælger
date_picker_previous_month = Forrige måned
date_picker_next_month = Næste måned
date_picker_previous_years = Forrige år
date_picker_next_years = Næste år
date_picker_choose_year = Vælg år
date_picker_month_january = januar
date_picker_month_february = februar
date_picker_month_march = marts
date_picker_month_april = april
date_picker_month_may = maj
date_picker_month_june = juni
date_picker_month_july = juli
date_picker_month_august = august
date_picker_month_september = september
date_picker_month_october = oktober
date_picker_month_november = november
date_picker_month_december = december
date_picker_weekday_sunday = sø.
date_picker_weekday_monday = ma.
date_picker_weekday_tuesday = ti.
date_picker_weekday_wednesday = on.
date_picker_weekday_thursday = to.
date_picker_weekday_friday = fr.
date_picker_weekday_saturday = lø.
time_picker = Tidsvælger
time_picker_hour = Time
time_picker_minute = Minut
time_picker_am = AM
time_picker_pm = PM
