dialog_ok = OK
dialog_cancel = Abbrechen
progress_in_progress = In Bearbeitung
refresh = Aktualisieren
text_selection_cut = Ausschneiden
text_selection_copy = Kopieren
text_selection_paste = Einfügen
text_selection_select_all = Alles auswählen
window_minimize = Minimieren
window_maximize = Maximieren
window_restore = Wiederherstellen
window_close = Schließen
validation_required = Dieses Feld ist erforderlich
validation_email = Geben Sie eine gültige E-Mail-Adresse ein
date_picker = Datumsauswahl
date_picker_previous_month = Vorheriger Monat
date_picker_next_month = Nächster Monat
date_picker_previous_years = Vorherige Jahre
date_picker_next_years = Nächste Jahre
date_picker_choose_year = Jahr auswählen
date_picker_month_january = Januar
date_picker_month_february = Februar
date_picker_month_march = März
date_picker_month_april = April
date_picker_month_may = Mai
date_picker_month_june = Juni
date_picker_month_july = Juli
date_picker_month_august = August
date_picker_month_september = September
date_picker_month_october = Oktober
date_picker_month_november = November
date_picker_month_december = Dezember
date_picker_weekday_sunday = So.
date_picker_weekday_monday = Mo.
date_picker_weekday_tuesday = Di.
date_picker_weekday_wednesday = Mi.
date_picker_weekday_thursday = Do.
date_picker_weekday_friday = Fr.
date_picker_weekday_saturday = Sa.
time_picker = Zeitauswahl
time_picker_hour = Stunde
time_picker_minute = Minute
time_picker_am = AM
time_picker_pm = PM
