dialog_ok = OK
dialog_cancel = Cancel
progress_in_progress = In progress
refresh = Refresh
text_selection_cut = Cut
text_selection_copy = Copy
text_selection_paste = Paste
text_selection_select_all = Select all
window_minimize = Minimize
window_maximize = Maximize
window_restore = Restore
window_close = Close
validation_required = This field is required
validation_email = Enter a valid email address
date_picker = Date picker
date_picker_previous_month = Previous month
date_picker_next_month = Next month
date_picker_previous_years = Previous years
date_picker_next_years = Next years
date_picker_choose_year = Choose year
date_picker_month_january = January
date_picker_month_february = February
date_picker_month_march = March
date_picker_month_april = April
date_picker_month_may = May
date_picker_month_june = June
date_picker_month_july = July
date_picker_month_august = August
date_picker_month_september = September
date_picker_month_october = October
date_picker_month_november = November
date_picker_month_december = December
date_picker_weekday_sunday = Sun
date_picker_weekday_monday = Mon
date_picker_weekday_tuesday = Tue
date_picker_weekday_wednesday = Wed
date_picker_weekday_thursday = Thu
date_picker_weekday_friday = Fri
date_picker_weekday_saturday = Sat
time_picker = Time picker
time_picker_hour = Hour
time_picker_minute = Minute
time_picker_am = AM
time_picker_pm = PM
