dialog_ok = OK
dialog_cancel = Ακύρωση
progress_in_progress = Σε εξέλιξη
text_selection_cut = Αποκοπή
text_selection_copy = Αντιγραφή
text_selection_paste = Επικόλληση
text_selection_select_all = Επιλογή όλων
window_minimize = Ελαχιστοποίηση
window_maximize = Μεγιστοποίηση
window_restore = Επαναφορά
window_close = Κλείσιμο
validation_required = Αυτό το πεδίο είναι υποχρεωτικό
validation_email = Εισαγάγετε μια έγκυρη διεύθυνση email
