dialog_ok = OK
dialog_cancel = Ακύρωση
progress_in_progress = Σε εξέλιξη
refresh = Ανανέωση
text_selection_cut = Αποκοπή
text_selection_copy = Αντιγραφή
text_selection_paste = Επικόλληση
text_selection_select_all = Επιλογή όλων
window_minimize = Ελαχιστοποίηση
window_maximize = Μεγιστοποίηση
window_restore = Επαναφορά
window_close = Κλείσιμο
validation_required = Αυτό το πεδίο είναι υποχρεωτικό
validation_email = Εισαγάγετε μια έγκυρη διεύθυνση email
date_picker = Επιλογή ημερομηνίας
date_picker_previous_month = Προηγούμενος μήνας
date_picker_next_month = Επόμενος μήνας
date_picker_previous_years = Προηγούμενα έτη
date_picker_next_years = Επόμενα έτη
date_picker_choose_year = Επιλογή έτους
date_picker_month_january = Ιανουάριος
date_picker_month_february = Φεβρουάριος
date_picker_month_march = Μάρτιος
date_picker_month_april = Απρίλιος
date_picker_month_may = Μάιος
date_picker_month_june = Ιούνιος
date_picker_month_july = Ιούλιος
date_picker_month_august = Αύγουστος
date_picker_month_september = Σεπτέμβριος
date_picker_month_october = Οκτώβριος
date_picker_month_november = Νοέμβριος
date_picker_month_december = Δεκέμβριος
date_picker_weekday_sunday = Κυ
date_picker_weekday_monday = Δε
date_picker_weekday_tuesday = Τρ
date_picker_weekday_wednesday = Τε
date_picker_weekday_thursday = Πέ
date_picker_weekday_friday = Πα
date_picker_weekday_saturday = Σά
time_picker = Επιλογή ώρας
time_picker_hour = Ώρα
time_picker_minute = Λεπτό
time_picker_am = π.μ.
time_picker_pm = μ.μ.
