dialog_ok = Aceptar
dialog_cancel = Cancelar
progress_in_progress = En curso
refresh = Actualizar
text_selection_cut = Cortar
text_selection_copy = Copiar
text_selection_paste = Pegar
text_selection_select_all = Seleccionar todo
window_minimize = Minimizar
window_maximize = Maximizar
window_restore = Restaurar
window_close = Cerrar
validation_required = Este campo es obligatorio
validation_email = Introduce una dirección de correo electrónico válida
date_picker = Selector de fecha
date_picker_previous_month = Mes anterior
date_picker_next_month = Mes siguiente
date_picker_previous_years = Años anteriores
date_picker_next_years = Años siguientes
date_picker_choose_year = Elegir año
date_picker_month_january = enero
date_picker_month_february = febrero
date_picker_month_march = marzo
date_picker_month_april = abril
date_picker_month_may = mayo
date_picker_month_june = junio
date_picker_month_july = julio
date_picker_month_august = agosto
date_picker_month_september = septiembre
date_picker_month_october = octubre
date_picker_month_november = noviembre
date_picker_month_december = diciembre
date_picker_weekday_sunday = DO
date_picker_weekday_monday = LU
date_picker_weekday_tuesday = MA
date_picker_weekday_wednesday = MI
date_picker_weekday_thursday = JU
date_picker_weekday_friday = VI
date_picker_weekday_saturday = SA
time_picker = Selector de hora
time_picker_hour = Hora
time_picker_minute = Minuto
time_picker_am = a. m.
time_picker_pm = p. m.
