dialog_ok = Aceptar
dialog_cancel = Cancelar
progress_in_progress = En curso
text_selection_cut = Cortar
text_selection_copy = Copiar
text_selection_paste = Pegar
text_selection_select_all = Seleccionar todo
window_minimize = Minimizar
window_maximize = Maximizar
window_restore = Restaurar
window_close = Cerrar
validation_required = Este campo es obligatorio
validation_email = Introduce una dirección de correo electrónico válida
