dialog_ok = تأیید
dialog_cancel = لغو
progress_in_progress = در حال انجام
refresh = تازه‌سازی
text_selection_cut = برش
text_selection_copy = کپی
text_selection_paste = جای‌گذاری
text_selection_select_all = انتخاب همه
window_minimize = کوچک کردن
window_maximize = بزرگ کردن
window_restore = بازیابی
window_close = بستن
validation_required = این فیلد الزامی است
validation_email = یک نشانی ایمیل معتبر وارد کنید
date_picker = انتخابگر تاریخ
date_picker_previous_month = ماه قبل
date_picker_next_month = ماه بعد
date_picker_previous_years = سال‌های قبل
date_picker_next_years = سال‌های بعد
date_picker_choose_year = انتخاب سال
date_picker_month_january = ژانویه
date_picker_month_february = فوریه
date_picker_month_march = مارس
date_picker_month_april = آوریل
date_picker_month_may = مه
date_picker_month_june = ژوئن
date_picker_month_july = ژوئیه
date_picker_month_august = اوت
date_picker_month_september = سپتامبر
date_picker_month_october = اکتبر
date_picker_month_november = نوامبر
date_picker_month_december = دسامبر
date_picker_weekday_sunday = ۱ش
date_picker_weekday_monday = ۲ش
date_picker_weekday_tuesday = ۳ش
date_picker_weekday_wednesday = ۴ش
date_picker_weekday_thursday = ۵ش
date_picker_weekday_friday = ج
date_picker_weekday_saturday = ش
time_picker = انتخابگر زمان
time_picker_hour = ساعت
time_picker_minute = دقیقه
time_picker_am = ق.ظ.
time_picker_pm = ب.ظ.
