dialog_ok = تأیید
dialog_cancel = لغو
text_selection_cut = برش
text_selection_copy = کپی
text_selection_paste = جای‌گذاری
text_selection_select_all = انتخاب همه
window_minimize = کوچک کردن
window_maximize = بزرگ کردن
window_restore = بازیابی
window_close = بستن
validation_required = این فیلد الزامی است
validation_email = یک نشانی ایمیل معتبر وارد کنید
