dialog_ok = OK
dialog_cancel = Peruuta
progress_in_progress = Käynnissä
refresh = Päivitä
text_selection_cut = Leikkaa
text_selection_copy = Kopioi
text_selection_paste = Liitä
text_selection_select_all = Valitse kaikki
window_minimize = Pienennä
window_maximize = Suurenna
window_restore = Palauta
window_close = Sulje
validation_required = Tämä kenttä on pakollinen
validation_email = Anna kelvollinen sähköpostiosoite
date_picker = Päivämäärän valitsin
date_picker_previous_month = Edellinen kuukausi
date_picker_next_month = Seuraava kuukausi
date_picker_previous_years = Edelliset vuodet
date_picker_next_years = Seuraavat vuodet
date_picker_choose_year = Valitse vuosi
date_picker_month_january = tammikuu
date_picker_month_february = helmikuu
date_picker_month_march = maaliskuu
date_picker_month_april = huhtikuu
date_picker_month_may = toukokuu
date_picker_month_june = kesäkuu
date_picker_month_july = heinäkuu
date_picker_month_august = elokuu
date_picker_month_september = syyskuu
date_picker_month_october = lokakuu
date_picker_month_november = marraskuu
date_picker_month_december = joulukuu
date_picker_weekday_sunday = su
date_picker_weekday_monday = ma
date_picker_weekday_tuesday = ti
date_picker_weekday_wednesday = ke
date_picker_weekday_thursday = to
date_picker_weekday_friday = pe
date_picker_weekday_saturday = la
time_picker = Kellonajan valitsin
time_picker_hour = Tunti
time_picker_minute = Minuutti
time_picker_am = ap.
time_picker_pm = ip.
