dialog_ok = OK
dialog_cancel = Peruuta
progress_in_progress = Käynnissä
refresh = Päivitä
text_selection_cut = Leikkaa
text_selection_copy = Kopioi
text_selection_paste = Liitä
text_selection_select_all = Valitse kaikki
window_minimize = Pienennä
window_maximize = Suurenna
window_restore = Palauta
window_close = Sulje
validation_required = Tämä kenttä on pakollinen
validation_email = Anna kelvollinen sähköpostiosoite
