dialog_ok = OK
dialog_cancel = Kanselahin
progress_in_progress = Isinasagawa
refresh = I-refresh
text_selection_cut = I-cut
text_selection_copy = Kopyahin
text_selection_paste = I-paste
text_selection_select_all = Piliin lahat
window_minimize = I-minimize
window_maximize = I-maximize
window_restore = I-restore
window_close = Isara
validation_required = Kinakailangan ang field na ito
validation_email = Maglagay ng wastong email address
date_picker = Tagapili ng petsa
date_picker_previous_month = Nakaraang buwan
date_picker_next_month = Susunod na buwan
date_picker_previous_years = Mga nakaraang taon
date_picker_next_years = Mga susunod na taon
date_picker_choose_year = Pumili ng taon
date_picker_month_january = Enero
date_picker_month_february = Pebrero
date_picker_month_march = Marso
date_picker_month_april = Abril
date_picker_month_may = Mayo
date_picker_month_june = Hunyo
date_picker_month_july = Hulyo
date_picker_month_august = Agosto
date_picker_month_september = Setyembre
date_picker_month_october = Oktubre
date_picker_month_november = Nobyembre
date_picker_month_december = Disyembre
date_picker_weekday_sunday = Lin
date_picker_weekday_monday = Lun
date_picker_weekday_tuesday = Mar
date_picker_weekday_wednesday = Miy
date_picker_weekday_thursday = Huw
date_picker_weekday_friday = Biy
date_picker_weekday_saturday = Sab
time_picker = Tagapili ng oras
time_picker_hour = Oras
time_picker_minute = Minuto
time_picker_am = AM
time_picker_pm = PM
