dialog_ok = OK
dialog_cancel = Kanselahin
progress_in_progress = Isinasagawa
text_selection_cut = I-cut
text_selection_copy = Kopyahin
text_selection_paste = I-paste
text_selection_select_all = Piliin lahat
window_minimize = I-minimize
window_maximize = I-maximize
window_restore = I-restore
window_close = Isara
validation_required = Kinakailangan ang field na ito
validation_email = Maglagay ng wastong email address
