dialog_ok = OK
dialog_cancel = Annuler
progress_in_progress = En cours
refresh = Actualiser
text_selection_cut = Couper
text_selection_copy = Copier
text_selection_paste = Coller
text_selection_select_all = Tout sélectionner
window_minimize = Réduire
window_maximize = Agrandir
window_restore = Restaurer
window_close = Fermer
validation_required = Ce champ est obligatoire
validation_email = Saisissez une adresse e-mail valide
