dialog_ok = OK
dialog_cancel = Annuler
progress_in_progress = En cours
refresh = Actualiser
text_selection_cut = Couper
text_selection_copy = Copier
text_selection_paste = Coller
text_selection_select_all = Tout sélectionner
window_minimize = Réduire
window_maximize = Agrandir
window_restore = Restaurer
window_close = Fermer
validation_required = Ce champ est obligatoire
validation_email = Saisissez une adresse e-mail valide
date_picker = Sélecteur de date
date_picker_previous_month = Mois précédent
date_picker_next_month = Mois suivant
date_picker_previous_years = Années précédentes
date_picker_next_years = Années suivantes
date_picker_choose_year = Choisir l’année
date_picker_month_january = janvier
date_picker_month_february = février
date_picker_month_march = mars
date_picker_month_april = avril
date_picker_month_may = mai
date_picker_month_june = juin
date_picker_month_july = juillet
date_picker_month_august = août
date_picker_month_september = septembre
date_picker_month_october = octobre
date_picker_month_november = novembre
date_picker_month_december = décembre
date_picker_weekday_sunday = di
date_picker_weekday_monday = lu
date_picker_weekday_tuesday = ma
date_picker_weekday_wednesday = me
date_picker_weekday_thursday = je
date_picker_weekday_friday = ve
date_picker_weekday_saturday = sa
time_picker = Sélecteur d’heure
time_picker_hour = Heure
time_picker_minute = Minute
time_picker_am = AM
time_picker_pm = PM
