dialog_ok = אישור
dialog_cancel = ביטול
progress_in_progress = בתהליך
text_selection_cut = גזירה
text_selection_copy = העתקה
text_selection_paste = הדבקה
text_selection_select_all = בחירת הכול
window_minimize = מזער
window_maximize = הגדל
window_restore = שחזר
window_close = סגור
validation_required = זהו שדה חובה
validation_email = יש להזין כתובת אימייל תקינה
