dialog_ok = אישור
dialog_cancel = ביטול
progress_in_progress = בתהליך
refresh = רענון
text_selection_cut = גזירה
text_selection_copy = העתקה
text_selection_paste = הדבקה
text_selection_select_all = בחירת הכול
window_minimize = מזער
window_maximize = הגדל
window_restore = שחזר
window_close = סגור
validation_required = זהו שדה חובה
validation_email = יש להזין כתובת אימייל תקינה
date_picker = בורר תאריך
date_picker_previous_month = החודש הקודם
date_picker_next_month = החודש הבא
date_picker_previous_years = השנים הקודמות
date_picker_next_years = השנים הבאות
date_picker_choose_year = בחירת שנה
date_picker_month_january = ינואר
date_picker_month_february = פברואר
date_picker_month_march = מרץ
date_picker_month_april = אפריל
date_picker_month_may = מאי
date_picker_month_june = יוני
date_picker_month_july = יולי
date_picker_month_august = אוגוסט
date_picker_month_september = ספטמבר
date_picker_month_october = אוקטובר
date_picker_month_november = נובמבר
date_picker_month_december = דצמבר
date_picker_weekday_sunday = א׳
date_picker_weekday_monday = ב׳
date_picker_weekday_tuesday = ג׳
date_picker_weekday_wednesday = ד׳
date_picker_weekday_thursday = ה׳
date_picker_weekday_friday = ו׳
date_picker_weekday_saturday = ש׳
time_picker = בורר שעה
time_picker_hour = שעה
time_picker_minute = דקה
time_picker_am = AM
time_picker_pm = PM
