dialog_ok = ठीक है
dialog_cancel = रद्द करें
progress_in_progress = प्रगति पर है
refresh = रीफ़्रेश
text_selection_cut = काटें
text_selection_copy = कॉपी करें
text_selection_paste = चिपकाएँ
text_selection_select_all = सभी चुनें
window_minimize = छोटा करें
window_maximize = बड़ा करें
window_restore = पुनर्स्थापित करें
window_close = बंद करें
validation_required = यह फ़ील्ड आवश्यक है
validation_email = एक मान्य ईमेल पता दर्ज करें
