dialog_ok = ठीक है
dialog_cancel = रद्द करें
progress_in_progress = प्रगति पर है
refresh = रीफ़्रेश
text_selection_cut = काटें
text_selection_copy = कॉपी करें
text_selection_paste = चिपकाएँ
text_selection_select_all = सभी चुनें
window_minimize = छोटा करें
window_maximize = बड़ा करें
window_restore = पुनर्स्थापित करें
window_close = बंद करें
validation_required = यह फ़ील्ड आवश्यक है
validation_email = एक मान्य ईमेल पता दर्ज करें
date_picker = तारीख चुनें
date_picker_previous_month = पिछला महीना
date_picker_next_month = अगला महीना
date_picker_previous_years = पिछले साल
date_picker_next_years = अगले साल
date_picker_choose_year = साल चुनें
date_picker_month_january = जनवरी
date_picker_month_february = फ़रवरी
date_picker_month_march = मार्च
date_picker_month_april = अप्रैल
date_picker_month_may = मई
date_picker_month_june = जून
date_picker_month_july = जुलाई
date_picker_month_august = अगस्त
date_picker_month_september = सितंबर
date_picker_month_october = अक्टूबर
date_picker_month_november = नवंबर
date_picker_month_december = दिसंबर
date_picker_weekday_sunday = र
date_picker_weekday_monday = सो
date_picker_weekday_tuesday = मं
date_picker_weekday_wednesday = बु
date_picker_weekday_thursday = गु
date_picker_weekday_friday = शु
date_picker_weekday_saturday = श
time_picker = समय चुनें
time_picker_hour = घंटा
time_picker_minute = मिनट
time_picker_am = am
time_picker_pm = pm
