dialog_ok = OK
dialog_cancel = Mégse
progress_in_progress = Folyamatban
refresh = Frissítés
text_selection_cut = Kivágás
text_selection_copy = Másolás
text_selection_paste = Beillesztés
text_selection_select_all = Összes kijelölése
window_minimize = Kis méret
window_maximize = Teljes méret
window_restore = Visszaállítás
window_close = Bezárás
validation_required = A mező kitöltése kötelező
validation_email = Adjon meg egy érvényes e-mail-címet
