dialog_ok = OK
dialog_cancel = Mégse
progress_in_progress = Folyamatban
refresh = Frissítés
text_selection_cut = Kivágás
text_selection_copy = Másolás
text_selection_paste = Beillesztés
text_selection_select_all = Összes kijelölése
window_minimize = Kis méret
window_maximize = Teljes méret
window_restore = Visszaállítás
window_close = Bezárás
validation_required = A mező kitöltése kötelező
validation_email = Adjon meg egy érvényes e-mail-címet
date_picker = Dátumválasztó
date_picker_previous_month = Előző hónap
date_picker_next_month = Következő hónap
date_picker_previous_years = Előző évek
date_picker_next_years = Következő évek
date_picker_choose_year = Év kiválasztása
date_picker_month_january = január
date_picker_month_february = február
date_picker_month_march = március
date_picker_month_april = április
date_picker_month_may = május
date_picker_month_june = június
date_picker_month_july = július
date_picker_month_august = augusztus
date_picker_month_september = szeptember
date_picker_month_october = október
date_picker_month_november = november
date_picker_month_december = december
date_picker_weekday_sunday = V
date_picker_weekday_monday = H
date_picker_weekday_tuesday = K
date_picker_weekday_wednesday = Sze
date_picker_weekday_thursday = Cs
date_picker_weekday_friday = P
date_picker_weekday_saturday = Szo
time_picker = Időválasztó
time_picker_hour = Óra
time_picker_minute = Perc
time_picker_am = de.
time_picker_pm = du.
