dialog_ok = OK
dialog_cancel = Batal
progress_in_progress = Sedang berlangsung
text_selection_cut = Potong
text_selection_copy = Salin
text_selection_paste = Tempel
text_selection_select_all = Pilih semua
window_minimize = Minimalkan
window_maximize = Maksimalkan
window_restore = Pulihkan
window_close = Tutup
validation_required = Kolom ini wajib diisi
validation_email = Masukkan alamat email yang valid
