dialog_ok = OK
dialog_cancel = Annulla
progress_in_progress = In corso
refresh = Aggiorna
text_selection_cut = Taglia
text_selection_copy = Copia
text_selection_paste = Incolla
text_selection_select_all = Seleziona tutto
window_minimize = Riduci a icona
window_maximize = Ingrandisci
window_restore = Ripristina
window_close = Chiudi
validation_required = Questo campo è obbligatorio
validation_email = Inserisci un indirizzo email valido
