dialog_ok = OK
dialog_cancel = Annulla
progress_in_progress = In corso
refresh = Aggiorna
text_selection_cut = Taglia
text_selection_copy = Copia
text_selection_paste = Incolla
text_selection_select_all = Seleziona tutto
window_minimize = Riduci a icona
window_maximize = Ingrandisci
window_restore = Ripristina
window_close = Chiudi
validation_required = Questo campo è obbligatorio
validation_email = Inserisci un indirizzo email valido
date_picker = Selettore di data
date_picker_previous_month = Mese precedente
date_picker_next_month = Mese successivo
date_picker_previous_years = Anni precedenti
date_picker_next_years = Anni successivi
date_picker_choose_year = Scegli l’anno
date_picker_month_january = gennaio
date_picker_month_february = febbraio
date_picker_month_march = marzo
date_picker_month_april = aprile
date_picker_month_may = maggio
date_picker_month_june = giugno
date_picker_month_july = luglio
date_picker_month_august = agosto
date_picker_month_september = settembre
date_picker_month_october = ottobre
date_picker_month_november = novembre
date_picker_month_december = dicembre
date_picker_weekday_sunday = dom
date_picker_weekday_monday = lun
date_picker_weekday_tuesday = mar
date_picker_weekday_wednesday = mer
date_picker_weekday_thursday = gio
date_picker_weekday_friday = ven
date_picker_weekday_saturday = sab
time_picker = Selettore di ora
time_picker_hour = Ora
time_picker_minute = Minuto
time_picker_am = AM
time_picker_pm = PM
