dialog_ok = OK
dialog_cancel = Batal
progress_in_progress = Sedang berlangsung
refresh = Muat semula
text_selection_cut = Potong
text_selection_copy = Salin
text_selection_paste = Tampal
text_selection_select_all = Pilih semua
window_minimize = Minimumkan
window_maximize = Maksimumkan
window_restore = Pulihkan
window_close = Tutup
validation_required = Medan ini diperlukan
validation_email = Masukkan alamat e-mel yang sah
