dialog_ok = OK
dialog_cancel = Batal
progress_in_progress = Sedang berlangsung
refresh = Muat semula
text_selection_cut = Potong
text_selection_copy = Salin
text_selection_paste = Tampal
text_selection_select_all = Pilih semua
window_minimize = Minimumkan
window_maximize = Maksimumkan
window_restore = Pulihkan
window_close = Tutup
validation_required = Medan ini diperlukan
validation_email = Masukkan alamat e-mel yang sah
date_picker = Pemilih tarikh
date_picker_previous_month = Bulan sebelumnya
date_picker_next_month = Bulan seterusnya
date_picker_previous_years = Tahun-tahun sebelumnya
date_picker_next_years = Tahun-tahun seterusnya
date_picker_choose_year = Pilih tahun
date_picker_month_january = Januari
date_picker_month_february = Februari
date_picker_month_march = Mac
date_picker_month_april = April
date_picker_month_may = Mei
date_picker_month_june = Jun
date_picker_month_july = Julai
date_picker_month_august = Ogos
date_picker_month_september = September
date_picker_month_october = Oktober
date_picker_month_november = November
date_picker_month_december = Disember
date_picker_weekday_sunday = Ah
date_picker_weekday_monday = Is
date_picker_weekday_tuesday = Se
date_picker_weekday_wednesday = Ra
date_picker_weekday_thursday = Kh
date_picker_weekday_friday = Ju
date_picker_weekday_saturday = Sa
time_picker = Pemilih masa
time_picker_hour = Jam
time_picker_minute = Minit
time_picker_am = PG
time_picker_pm = PTG
