dialog_ok = OK
dialog_cancel = Avbryt
progress_in_progress = Pågår
refresh = Oppdater
text_selection_cut = Klipp ut
text_selection_copy = Kopier
text_selection_paste = Lim inn
text_selection_select_all = Merk alt
window_minimize = Minimer
window_maximize = Maksimer
window_restore = Gjenopprett
window_close = Lukk
validation_required = Dette feltet er obligatorisk
validation_email = Skriv inn en gyldig e-postadresse
date_picker = Datovelger
date_picker_previous_month = Forrige måned
date_picker_next_month = Neste måned
date_picker_previous_years = Forrige år
date_picker_next_years = Neste år
date_picker_choose_year = Velg år
date_picker_month_january = januar
date_picker_month_february = februar
date_picker_month_march = mars
date_picker_month_april = april
date_picker_month_may = mai
date_picker_month_june = juni
date_picker_month_july = juli
date_picker_month_august = august
date_picker_month_september = september
date_picker_month_october = oktober
date_picker_month_november = november
date_picker_month_december = desember
date_picker_weekday_sunday = sø.
date_picker_weekday_monday = ma.
date_picker_weekday_tuesday = ti.
date_picker_weekday_wednesday = on.
date_picker_weekday_thursday = to.
date_picker_weekday_friday = fr.
date_picker_weekday_saturday = lø.
time_picker = Tidsvelger
time_picker_hour = Time
time_picker_minute = Minutt
time_picker_am = a.m.
time_picker_pm = p.m.
