dialog_ok = OK
dialog_cancel = Avbryt
progress_in_progress = Pågår
refresh = Oppdater
text_selection_cut = Klipp ut
text_selection_copy = Kopier
text_selection_paste = Lim inn
text_selection_select_all = Merk alt
window_minimize = Minimer
window_maximize = Maksimer
window_restore = Gjenopprett
window_close = Lukk
validation_required = Dette feltet er obligatorisk
validation_email = Skriv inn en gyldig e-postadresse
