dialog_ok = OK
dialog_cancel = Anuluj
progress_in_progress = W toku
refresh = Odśwież
text_selection_cut = Wytnij
text_selection_copy = Kopiuj
text_selection_paste = Wklej
text_selection_select_all = Zaznacz wszystko
window_minimize = Minimalizuj
window_maximize = Maksymalizuj
window_restore = Przywróć
window_close = Zamknij
validation_required = To pole jest wymagane
validation_email = Wprowadź prawidłowy adres e-mail
date_picker = Wybór daty
date_picker_previous_month = Poprzedni miesiąc
date_picker_next_month = Następny miesiąc
date_picker_previous_years = Poprzednie lata
date_picker_next_years = Następne lata
date_picker_choose_year = Wybierz rok
date_picker_month_january = styczeń
date_picker_month_february = luty
date_picker_month_march = marzec
date_picker_month_april = kwiecień
date_picker_month_may = maj
date_picker_month_june = czerwiec
date_picker_month_july = lipiec
date_picker_month_august = sierpień
date_picker_month_september = wrzesień
date_picker_month_october = październik
date_picker_month_november = listopad
date_picker_month_december = grudzień
date_picker_weekday_sunday = nie
date_picker_weekday_monday = pon
date_picker_weekday_tuesday = wto
date_picker_weekday_wednesday = śro
date_picker_weekday_thursday = czw
date_picker_weekday_friday = pią
date_picker_weekday_saturday = sob
time_picker = Wybór godziny
time_picker_hour = Godzina
time_picker_minute = Minuta
time_picker_am = AM
time_picker_pm = PM
