dialog_ok = OK
dialog_cancel = Cancelar
text_selection_cut = Cortar
text_selection_copy = Copiar
text_selection_paste = Colar
text_selection_select_all = Selecionar tudo
window_minimize = Minimizar
window_maximize = Maximizar
window_restore = Restaurar
window_close = Fechar
validation_required = Este campo é obrigatório
validation_email = Introduza um endereço de e-mail válido
