dialog_ok = OK
dialog_cancel = Cancelar
progress_in_progress = Em curso
refresh = Atualizar
text_selection_cut = Recortar
text_selection_copy = Copiar
text_selection_paste = Colar
text_selection_select_all = Selecionar tudo
window_minimize = Minimizar
window_maximize = Maximizar
window_restore = Restaurar
window_close = Fechar
validation_required = Este campo é obrigatório
validation_email = Insira um endereço de e-mail válido
date_picker = Seletor de data
date_picker_previous_month = Mês anterior
date_picker_next_month = Mês seguinte
date_picker_previous_years = Anos anteriores
date_picker_next_years = Anos seguintes
date_picker_choose_year = Selecionar ano
date_picker_month_january = janeiro
date_picker_month_february = fevereiro
date_picker_month_march = março
date_picker_month_april = abril
date_picker_month_may = maio
date_picker_month_june = junho
date_picker_month_july = julho
date_picker_month_august = agosto
date_picker_month_september = setembro
date_picker_month_october = outubro
date_picker_month_november = novembro
date_picker_month_december = dezembro
date_picker_weekday_sunday = dom.
date_picker_weekday_monday = seg.
date_picker_weekday_tuesday = ter.
date_picker_weekday_wednesday = qua.
date_picker_weekday_thursday = qui.
date_picker_weekday_friday = sex.
date_picker_weekday_saturday = sáb.
time_picker = Seletor de hora
time_picker_hour = Hora
time_picker_minute = Minuto
time_picker_am = AM
time_picker_pm = PM
