dialog_ok = OK
dialog_cancel = Anulați
text_selection_cut = Decupați
text_selection_copy = Copiați
text_selection_paste = Lipiți
text_selection_select_all = Selectați tot
window_minimize = Minimizare
window_maximize = Maximizare
window_restore = Restabilire
window_close = Închidere
validation_required = Acest câmp este obligatoriu
validation_email = Introduceți o adresă de e-mail validă
