dialog_ok = OK
dialog_cancel = Anulați
progress_in_progress = În desfășurare
refresh = Reîmprospătare
text_selection_cut = Decupați
text_selection_copy = Copiați
text_selection_paste = Lipiți
text_selection_select_all = Selectați tot
window_minimize = Minimizare
window_maximize = Maximizare
window_restore = Restabilire
window_close = Închidere
validation_required = Acest câmp este obligatoriu
validation_email = Introduceți o adresă de e-mail validă
date_picker = Selector de dată
date_picker_previous_month = Luna anterioară
date_picker_next_month = Luna următoare
date_picker_previous_years = Anii anteriori
date_picker_next_years = Anii următori
date_picker_choose_year = Alege anul
date_picker_month_january = ianuarie
date_picker_month_february = februarie
date_picker_month_march = martie
date_picker_month_april = aprilie
date_picker_month_may = mai
date_picker_month_june = iunie
date_picker_month_july = iulie
date_picker_month_august = august
date_picker_month_september = septembrie
date_picker_month_october = octombrie
date_picker_month_november = noiembrie
date_picker_month_december = decembrie
date_picker_weekday_sunday = du.
date_picker_weekday_monday = lu.
date_picker_weekday_tuesday = ma.
date_picker_weekday_wednesday = mi.
date_picker_weekday_thursday = joi
date_picker_weekday_friday = vi.
date_picker_weekday_saturday = sâ.
time_picker = Selector de oră
time_picker_hour = Oră
time_picker_minute = Minut
time_picker_am = a.m.
time_picker_pm = p.m.
