dialog_ok = ОК
dialog_cancel = Отмена
progress_in_progress = Выполняется
refresh = Обновить
text_selection_cut = Вырезать
text_selection_copy = Копировать
text_selection_paste = Вставить
text_selection_select_all = Выбрать всё
window_minimize = Свернуть
window_maximize = Развернуть
window_restore = Восстановить
window_close = Закрыть
validation_required = Это поле обязательно
validation_email = Введите действительный адрес электронной почты
date_picker = Выбор даты
date_picker_previous_month = Предыдущий месяц
date_picker_next_month = Следующий месяц
date_picker_previous_years = Предыдущие годы
date_picker_next_years = Следующие годы
date_picker_choose_year = Выбрать год
date_picker_month_january = январь
date_picker_month_february = февраль
date_picker_month_march = март
date_picker_month_april = апрель
date_picker_month_may = май
date_picker_month_june = июнь
date_picker_month_july = июль
date_picker_month_august = август
date_picker_month_september = сентябрь
date_picker_month_october = октябрь
date_picker_month_november = ноябрь
date_picker_month_december = декабрь
date_picker_weekday_sunday = вс
date_picker_weekday_monday = пн
date_picker_weekday_tuesday = вт
date_picker_weekday_wednesday = ср
date_picker_weekday_thursday = чт
date_picker_weekday_friday = пт
date_picker_weekday_saturday = сб
time_picker = Выбор времени
time_picker_hour = Час
time_picker_minute = Минута
time_picker_am = AM
time_picker_pm = PM
