dialog_ok = OK
dialog_cancel = Avbryt
progress_in_progress = Pågår
refresh = Uppdatera
text_selection_cut = Klipp ut
text_selection_copy = Kopiera
text_selection_paste = Klistra in
text_selection_select_all = Markera allt
window_minimize = Minimera
window_maximize = Maximera
window_restore = Återställ
window_close = Stäng
validation_required = Det här fältet är obligatoriskt
validation_email = Ange en giltig e-postadress
date_picker = Datumväljare
date_picker_previous_month = Föregående månad
date_picker_next_month = Nästa månad
date_picker_previous_years = Föregående år
date_picker_next_years = Nästa år
date_picker_choose_year = Välj år
date_picker_month_january = januari
date_picker_month_february = februari
date_picker_month_march = mars
date_picker_month_april = april
date_picker_month_may = maj
date_picker_month_june = juni
date_picker_month_july = juli
date_picker_month_august = augusti
date_picker_month_september = september
date_picker_month_october = oktober
date_picker_month_november = november
date_picker_month_december = december
date_picker_weekday_sunday = sö
date_picker_weekday_monday = må
date_picker_weekday_tuesday = ti
date_picker_weekday_wednesday = on
date_picker_weekday_thursday = to
date_picker_weekday_friday = fr
date_picker_weekday_saturday = lö
time_picker = Tidsväljare
time_picker_hour = Timme
time_picker_minute = Minut
time_picker_am = fm
time_picker_pm = em
