dialog_ok = OK
dialog_cancel = Avbryt
text_selection_cut = Klipp ut
text_selection_copy = Kopiera
text_selection_paste = Klistra in
text_selection_select_all = Markera allt
window_minimize = Minimera
window_maximize = Maximera
window_restore = Återställ
window_close = Stäng
validation_required = Det här fältet är obligatoriskt
validation_email = Ange en giltig e-postadress
