dialog_ok = ตกลง
dialog_cancel = ยกเลิก
progress_in_progress = กำลังดำเนินการ
text_selection_cut = ตัด
text_selection_copy = คัดลอก
text_selection_paste = วาง
text_selection_select_all = เลือกทั้งหมด
window_minimize = ย่อเล็กสุด
window_maximize = ขยายใหญ่สุด
window_restore = คืนค่า
window_close = ปิด
validation_required = ต้องกรอกข้อมูลในช่องนี้
validation_email = ป้อนที่อยู่อีเมลที่ถูกต้อง
