dialog_ok = ตกลง
dialog_cancel = ยกเลิก
progress_in_progress = กำลังดำเนินการ
refresh = รีเฟรช
text_selection_cut = ตัด
text_selection_copy = คัดลอก
text_selection_paste = วาง
text_selection_select_all = เลือกทั้งหมด
window_minimize = ย่อเล็กสุด
window_maximize = ขยายใหญ่สุด
window_restore = คืนค่า
window_close = ปิด
validation_required = ต้องกรอกข้อมูลในช่องนี้
validation_email = ป้อนที่อยู่อีเมลที่ถูกต้อง
date_picker = ตัวเลือกวันที่
date_picker_previous_month = เดือนก่อนหน้า
date_picker_next_month = เดือนถัดไป
date_picker_previous_years = ปีก่อนหน้า
date_picker_next_years = ปีถัดไป
date_picker_choose_year = เลือกปี
date_picker_month_january = มกราคม
date_picker_month_february = กุมภาพันธ์
date_picker_month_march = มีนาคม
date_picker_month_april = เมษายน
date_picker_month_may = พฤษภาคม
date_picker_month_june = มิถุนายน
date_picker_month_july = กรกฎาคม
date_picker_month_august = สิงหาคม
date_picker_month_september = กันยายน
date_picker_month_october = ตุลาคม
date_picker_month_november = พฤศจิกายน
date_picker_month_december = ธันวาคม
date_picker_weekday_sunday = อา.
date_picker_weekday_monday = จ.
date_picker_weekday_tuesday = อ.
date_picker_weekday_wednesday = พ.
date_picker_weekday_thursday = พฤ.
date_picker_weekday_friday = ศ.
date_picker_weekday_saturday = ส.
time_picker = ตัวเลือกเวลา
time_picker_hour = ชั่วโมง
time_picker_minute = นาที
time_picker_am = AM
time_picker_pm = PM
