dialog_ok = Tamam
dialog_cancel = İptal
progress_in_progress = Devam ediyor
text_selection_cut = Kes
text_selection_copy = Kopyala
text_selection_paste = Yapıştır
text_selection_select_all = Tümünü seç
window_minimize = Simge durumuna küçült
window_maximize = Ekranı kapla
window_restore = Geri yükle
window_close = Kapat
validation_required = Bu alan zorunludur
validation_email = Geçerli bir e-posta adresi girin
