dialog_ok = Tamam
dialog_cancel = İptal
progress_in_progress = Devam ediyor
refresh = Yenile
text_selection_cut = Kes
text_selection_copy = Kopyala
text_selection_paste = Yapıştır
text_selection_select_all = Tümünü seç
window_minimize = Simge durumuna küçült
window_maximize = Ekranı kapla
window_restore = Geri yükle
window_close = Kapat
validation_required = Bu alan zorunludur
validation_email = Geçerli bir e-posta adresi girin
date_picker = Tarih seçici
date_picker_previous_month = Önceki ay
date_picker_next_month = Sonraki ay
date_picker_previous_years = Önceki yıllar
date_picker_next_years = Sonraki yıllar
date_picker_choose_year = Yıl seç
date_picker_month_january = Ocak
date_picker_month_february = Şubat
date_picker_month_march = Mart
date_picker_month_april = Nisan
date_picker_month_may = Mayıs
date_picker_month_june = Haziran
date_picker_month_july = Temmuz
date_picker_month_august = Ağustos
date_picker_month_september = Eylül
date_picker_month_october = Ekim
date_picker_month_november = Kasım
date_picker_month_december = Aralık
date_picker_weekday_sunday = Pa
date_picker_weekday_monday = Pt
date_picker_weekday_tuesday = Sa
date_picker_weekday_wednesday = Ça
date_picker_weekday_thursday = Pe
date_picker_weekday_friday = Cu
date_picker_weekday_saturday = Ct
time_picker = Saat seçici
time_picker_hour = Saat
time_picker_minute = Dakika
time_picker_am = ÖÖ
time_picker_pm = ÖS
