dialog_ok = OK
dialog_cancel = Скасувати
progress_in_progress = Виконується
refresh = Оновити
text_selection_cut = Вирізати
text_selection_copy = Копіювати
text_selection_paste = Вставити
text_selection_select_all = Вибрати все
window_minimize = Згорнути
window_maximize = Розгорнути
window_restore = Відновити
window_close = Закрити
validation_required = Це поле обов’язкове
validation_email = Введіть дійсну адресу електронної пошти
date_picker = Вибір дати
date_picker_previous_month = Попередній місяць
date_picker_next_month = Наступний місяць
date_picker_previous_years = Попередні роки
date_picker_next_years = Наступні роки
date_picker_choose_year = Вибрати рік
date_picker_month_january = січень
date_picker_month_february = лютий
date_picker_month_march = березень
date_picker_month_april = квітень
date_picker_month_may = травень
date_picker_month_june = червень
date_picker_month_july = липень
date_picker_month_august = серпень
date_picker_month_september = вересень
date_picker_month_october = жовтень
date_picker_month_november = листопад
date_picker_month_december = грудень
date_picker_weekday_sunday = нд
date_picker_weekday_monday = пн
date_picker_weekday_tuesday = вт
date_picker_weekday_wednesday = ср
date_picker_weekday_thursday = чт
date_picker_weekday_friday = пт
date_picker_weekday_saturday = сб
time_picker = Вибір часу
time_picker_hour = Година
time_picker_minute = Хвилина
time_picker_am = дп
time_picker_pm = пп
