dialog_ok = OK
dialog_cancel = Скасувати
progress_in_progress = Виконується
refresh = Оновити
text_selection_cut = Вирізати
text_selection_copy = Копіювати
text_selection_paste = Вставити
text_selection_select_all = Вибрати все
window_minimize = Згорнути
window_maximize = Розгорнути
window_restore = Відновити
window_close = Закрити
validation_required = Це поле обов’язкове
validation_email = Введіть дійсну адресу електронної пошти
