dialog_ok = ٹھیک ہے
dialog_cancel = منسوخ کریں
progress_in_progress = جاری ہے
refresh = تازہ کریں
text_selection_cut = کاٹیں
text_selection_copy = کاپی کریں
text_selection_paste = چسپاں کریں
text_selection_select_all = سبھی منتخب کریں
window_minimize = چھوٹا کریں
window_maximize = بڑا کریں
window_restore = بحال کریں
window_close = بند کریں
validation_required = یہ فیلڈ لازمی ہے
validation_email = ایک درست ای میل پتہ درج کریں
