dialog_ok = OK
dialog_cancel = Hủy
progress_in_progress = Đang tiến hành
refresh = Làm mới
text_selection_cut = Cắt
text_selection_copy = Sao chép
text_selection_paste = Dán
text_selection_select_all = Chọn tất cả
window_minimize = Thu nhỏ
window_maximize = Phóng to
window_restore = Khôi phục
window_close = Đóng
validation_required = Trường này là bắt buộc
validation_email = Nhập địa chỉ email hợp lệ
date_picker = Bộ chọn ngày
date_picker_previous_month = Tháng trước
date_picker_next_month = Tháng sau
date_picker_previous_years = Các năm trước
date_picker_next_years = Các năm sau
date_picker_choose_year = Chọn năm
date_picker_month_january = Tháng 1
date_picker_month_february = Tháng 2
date_picker_month_march = Tháng 3
date_picker_month_april = Tháng 4
date_picker_month_may = Tháng 5
date_picker_month_june = Tháng 6
date_picker_month_july = Tháng 7
date_picker_month_august = Tháng 8
date_picker_month_september = Tháng 9
date_picker_month_october = Tháng 10
date_picker_month_november = Tháng 11
date_picker_month_december = Tháng 12
date_picker_weekday_sunday = CN
date_picker_weekday_monday = T2
date_picker_weekday_tuesday = T3
date_picker_weekday_wednesday = T4
date_picker_weekday_thursday = T5
date_picker_weekday_friday = T6
date_picker_weekday_saturday = T7
time_picker = Bộ chọn giờ
time_picker_hour = Giờ
time_picker_minute = Phút
time_picker_am = SA
time_picker_pm = CH
