dialog_ok = OK
dialog_cancel = Hủy
progress_in_progress = Đang tiến hành
refresh = Làm mới
text_selection_cut = Cắt
text_selection_copy = Sao chép
text_selection_paste = Dán
text_selection_select_all = Chọn tất cả
window_minimize = Thu nhỏ
window_maximize = Phóng to
window_restore = Khôi phục
window_close = Đóng
validation_required = Trường này là bắt buộc
validation_email = Nhập địa chỉ email hợp lệ
