dialog_ok = 確定
dialog_cancel = 取消
progress_in_progress = 進行中
refresh = 重新整理
text_selection_cut = 剪下
text_selection_copy = 複製
text_selection_paste = 貼上
text_selection_select_all = 全選
window_minimize = 最小化
window_maximize = 最大化
window_restore = 還原
window_close = 關閉
validation_required = 此欄位必須填寫
validation_email = 請輸入有效的電郵地址
