dialog_ok = 确定
dialog_cancel = 取消
progress_in_progress = 进行中
refresh = 刷新
text_selection_cut = 剪切
text_selection_copy = 复制
text_selection_paste = 粘贴
text_selection_select_all = 全选
window_minimize = 最小化
window_maximize = 最大化
window_restore = 还原
window_close = 关闭
validation_required = 此字段为必填项
validation_email = 请输入有效的电子邮件地址
date_picker = 日期选择器
date_picker_previous_month = 上个月
date_picker_next_month = 下个月
date_picker_previous_years = 上一组年份
date_picker_next_years = 下一组年份
date_picker_choose_year = 选择年份
date_picker_month_january = 1月
date_picker_month_february = 2月
date_picker_month_march = 3月
date_picker_month_april = 4月
date_picker_month_may = 5月
date_picker_month_june = 6月
date_picker_month_july = 7月
date_picker_month_august = 8月
date_picker_month_september = 9月
date_picker_month_october = 10月
date_picker_month_november = 11月
date_picker_month_december = 12月
date_picker_weekday_sunday = 日
date_picker_weekday_monday = 一
date_picker_weekday_tuesday = 二
date_picker_weekday_wednesday = 三
date_picker_weekday_thursday = 四
date_picker_weekday_friday = 五
date_picker_weekday_saturday = 六
time_picker = 时间选择器
time_picker_hour = 小时
time_picker_minute = 分钟
time_picker_am = 上午
time_picker_pm = 下午
