org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
huxeruiCompileSdk=@ANDROID_COMPILE_SDK@
huxeruiMinCompileSdk=@ANDROID_MIN_COMPILE_SDK@
huxeruiMinSdk=@ANDROID_MIN_SDK@
huxeruiTargetSdk=@ANDROID_TARGET_SDK@
huxeruiNdkVersion=@ANDROID_NDK_VERSION@
huxeruiAbis=arm64-v8a,x86_64
huxeruiStl=c++_shared
huxeruiBuildNative=false
